import { prisma } from "@/lib/prisma";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ExpensesTable } from "./expenses-table";
import { calcTotalWithTax } from "@/lib/finance/auto-generate";

export default async function ExpensesPage() {
  const [records, agents, stpCompanies] = await Promise.all([
    prisma.stpExpenseRecord.findMany({
      where: { deletedAt: null },
      include: {
        agent: {
          include: { company: true },
        },
        stpCompany: {
          include: { company: true },
        },
        invoice: true,
        paymentAllocations: true,
      },
      orderBy: [{ targetMonth: "desc" }, { id: "desc" }],
    }),
    prisma.stpAgent.findMany({
      include: { company: true },
      orderBy: { id: "asc" },
    }),
    prisma.stpCompany.findMany({
      include: { company: true },
      orderBy: { id: "asc" },
    }),
  ]);

  const formatDate = (date: Date | null): string | null => {
    if (!date) return null;
    return date.toISOString().split("T")[0];
  };

  const agentOptions = agents.map((a) => ({
    value: String(a.id),
    label: a.company.name,
  }));

  const stpCompanyOptions = stpCompanies.map((sc) => ({
    value: String(sc.id),
    label: `${sc.company.companyCode} ${sc.company.name}`,
  }));

  const data = records.map((r) => ({
    id: r.id,
    agentId: String(r.agentId),
    agentDisplay: r.agent.company.name,
    stpCompanyId: r.stpCompanyId ? String(r.stpCompanyId) : null,
    stpCompanyCode: r.stpCompany?.company?.companyCode || null,
    stpCompanyDisplay: r.stpCompany?.company?.name || null,
    agentContractHistoryId: r.agentContractHistoryId
      ? String(r.agentContractHistoryId)
      : null,
    contractHistoryId: r.contractHistoryId
      ? String(r.contractHistoryId)
      : null,
    revenueRecordId: r.revenueRecordId
      ? String(r.revenueRecordId)
      : null,
    expenseType: r.expenseType,
    targetMonth: formatDate(r.targetMonth),
    expectedAmount: r.expectedAmount,
    status: r.status,
    paymentStatus: r.paymentStatus,
    approvedDate: formatDate(r.approvedDate),
    paidDate: formatDate(r.paidDate),
    paidAmount: r.paidAmount,
    accountingStatus: r.accountingStatus,
    accountingService: r.accountingService,
    accountingExternalId: r.accountingExternalId,
    accountingSyncedAt: formatDate(r.accountingSyncedAt),
    taxType: r.taxType,
    taxRate: r.taxRate,
    taxAmount: r.taxAmount,
    isAutoGenerated: r.isAutoGenerated,
    sourceDataChangedAt: r.sourceDataChangedAt?.toISOString() || null,
    latestCalculatedAmount: r.latestCalculatedAmount,
    note: r.note,
    // 源泉徴収
    isWithholdingTarget: r.isWithholdingTarget,
    withholdingTaxAmount: r.withholdingTaxAmount,
    netPaymentAmount: r.netPaymentAmount,
    // 報酬率スナップショット
    appliedCommissionRate: r.appliedCommissionRate ? Number(r.appliedCommissionRate) : null,
    appliedCommissionType: r.appliedCommissionType,
    // 消込状況
    totalAllocated: r.paymentAllocations.reduce((sum, a) => sum + a.allocatedAmount, 0),
    // 請求書情報（invoiceリレーション経由）
    invoiceId: r.invoice?.id || null,
    invoiceStatus: r.invoice?.status || null,
    invoiceNumber: r.invoice?.invoiceNumber || null,
    invoiceFileName: r.invoice?.fileName || null,
  }));

  // サマリー計算（税込合計で集計）
  const totalExpected = records.reduce(
    (sum, r) => sum + calcTotalWithTax(r.expectedAmount, r.taxType, r.taxRate),
    0
  );
  const totalPaid = records
    .filter((r) => r.status === "paid")
    .reduce((sum, r) => sum + (r.paidAmount || calcTotalWithTax(r.expectedAmount, r.taxType, r.taxRate)), 0);
  const pendingCount = records.filter(
    (r) => r.status === "pending" || r.status === "approved"
  ).length;
  const sourceChangedCount = records.filter((r) => r.sourceDataChangedAt != null).length;

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold">経費管理</h1>

      <div className={`grid grid-cols-1 gap-4 ${sourceChangedCount > 0 ? "sm:grid-cols-4" : "sm:grid-cols-3"}`}>
        <Card>
          <CardContent className="pt-6">
            <div className="text-sm text-muted-foreground">支払予定総額</div>
            <div className="text-2xl font-bold">
              ¥{totalExpected.toLocaleString()}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-sm text-muted-foreground">支払済</div>
            <div className="text-2xl font-bold text-green-600">
              ¥{totalPaid.toLocaleString()}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-sm text-muted-foreground">未支払件数</div>
            <div className="text-2xl font-bold text-orange-600">
              {pendingCount}件
            </div>
          </CardContent>
        </Card>
        {sourceChangedCount > 0 && (
          <Card>
            <CardContent className="pt-6">
              <div className="text-sm text-muted-foreground">要確認</div>
              <div className="text-2xl font-bold text-orange-600">
                {sourceChangedCount}件
              </div>
            </CardContent>
          </Card>
        )}
      </div>

      <Card>
        <CardHeader>
          <CardTitle>経費一覧</CardTitle>
        </CardHeader>
        <CardContent>
          <ExpensesTable
            data={data}
            agentOptions={agentOptions}
            stpCompanyOptions={stpCompanyOptions}
          />
        </CardContent>
      </Card>
    </div>
  );
}
