import { prisma } from "@/lib/prisma";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { RevenueTable } from "./revenue-table";
import { calcTotalWithTax } from "@/lib/finance/auto-generate";

export default async function RevenuePage() {
  const [records, stpCompanies, contractHistories, candidates] =
    await Promise.all([
      prisma.stpRevenueRecord.findMany({
        where: { deletedAt: null },
        include: {
          stpCompany: {
            include: { company: true },
          },
          contractHistory: true,
          candidate: true,
          invoice: true,
          paymentAllocations: true,
        },
        orderBy: [{ targetMonth: "desc" }, { id: "desc" }],
      }),
      prisma.stpCompany.findMany({
        include: { company: true },
        orderBy: { id: "asc" },
      }),
      prisma.stpContractHistory.findMany({
        include: { company: true },
        where: { deletedAt: null },
        orderBy: { contractStartDate: "desc" },
      }),
      prisma.stpCandidate.findMany({
        orderBy: { id: "asc" },
      }),
    ]);

  const formatDate = (date: Date | null): string | null => {
    if (!date) return null;
    return date.toISOString().split("T")[0];
  };

  const stpCompanyOptions = stpCompanies.map((sc) => ({
    value: String(sc.id),
    label: `${sc.company.companyCode} ${sc.company.name}`,
  }));

  const contractHistoryOptions = contractHistories.map((ch) => ({
    value: String(ch.id),
    label: `${ch.company.name} - ${ch.contractPlan} (${formatDate(ch.contractStartDate)}〜)`,
  }));

  const candidateOptions = candidates.map((c) => ({
    value: String(c.id),
    label: `${c.lastName} ${c.firstName}`,
  }));

  const data = records.map((r) => ({
    id: r.id,
    stpCompanyId: String(r.stpCompanyId),
    stpCompanyCode: r.stpCompany.company.companyCode,
    stpCompanyDisplay: r.stpCompany.company.name,
    contractHistoryId: r.contractHistoryId
      ? String(r.contractHistoryId)
      : null,
    candidateId: r.candidateId ? String(r.candidateId) : null,
    revenueType: r.revenueType,
    targetMonth: formatDate(r.targetMonth),
    expectedAmount: r.expectedAmount,
    status: r.status,
    paymentStatus: r.paymentStatus,
    invoiceDate: formatDate(r.invoiceDate),
    dueDate: formatDate(r.dueDate),
    paidDate: formatDate(r.paidDate),
    paidAmount: r.paidAmount,
    accountingStatus: r.accountingStatus,
    accountingService: r.accountingService,
    accountingExternalId: r.accountingExternalId,
    accountingSyncedAt: formatDate(r.accountingSyncedAt),
    taxType: r.taxType,
    taxRate: r.taxRate,
    taxAmount: r.taxAmount,
    isAutoGenerated: r.isAutoGenerated,
    sourceDataChangedAt: r.sourceDataChangedAt?.toISOString() || null,
    latestCalculatedAmount: r.latestCalculatedAmount,
    note: r.note,
    // 承認情報
    approvedAt: r.approvedAt?.toISOString() || null,
    approvedBy: r.approvedBy,
    // 消込状況
    totalAllocated: r.paymentAllocations.reduce((sum, a) => sum + a.allocatedAmount, 0),
    // 請求書情報（invoiceリレーション経由）
    invoiceId: r.invoice?.id || null,
    invoiceStatus: r.invoice?.status || null,
    invoiceNumber: r.invoice?.invoiceNumber || null,
    invoiceFileName: r.invoice?.fileName || null,
    invoiceFilePath: r.invoice?.filePath || null,
  }));

  // サマリー計算（税込合計で集計）
  const totalExpected = records.reduce(
    (sum, r) => sum + calcTotalWithTax(r.expectedAmount, r.taxType, r.taxRate),
    0
  );
  const totalPaid = records
    .filter((r) => r.status === "paid")
    .reduce((sum, r) => sum + (r.paidAmount || calcTotalWithTax(r.expectedAmount, r.taxType, r.taxRate)), 0);
  const pendingCount = records.filter(
    (r) => r.status === "pending" || r.status === "invoiced"
  ).length;
  const overdueCount = records.filter((r) => r.status === "overdue").length;
  const sourceChangedCount = records.filter((r) => r.sourceDataChangedAt != null).length;

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold">売上管理</h1>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-5">
        <Card>
          <CardContent className="pt-6">
            <div className="text-sm text-muted-foreground">請求総額</div>
            <div className="text-2xl font-bold">
              ¥{totalExpected.toLocaleString()}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-sm text-muted-foreground">入金済</div>
            <div className="text-2xl font-bold text-green-600">
              ¥{totalPaid.toLocaleString()}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-sm text-muted-foreground">未入金件数</div>
            <div className="text-2xl font-bold text-blue-600">
              {pendingCount}件
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-sm text-muted-foreground">期限超過</div>
            <div className="text-2xl font-bold text-red-600">
              {overdueCount}件
            </div>
          </CardContent>
        </Card>
        {sourceChangedCount > 0 && (
          <Card>
            <CardContent className="pt-6">
              <div className="text-sm text-muted-foreground">要確認</div>
              <div className="text-2xl font-bold text-orange-600">
                {sourceChangedCount}件
              </div>
            </CardContent>
          </Card>
        )}
      </div>

      <Card>
        <CardHeader>
          <CardTitle>売上一覧</CardTitle>
        </CardHeader>
        <CardContent>
          <RevenueTable
            data={data}
            stpCompanyOptions={stpCompanyOptions}
            contractHistoryOptions={contractHistoryOptions}
            candidateOptions={candidateOptions}
          />
        </CardContent>
      </Card>
    </div>
  );
}
