"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { toast } from "sonner";
import {
  ArrowLeft,
  RefreshCw,
  ExternalLink,
  Presentation,
  Loader2,
  FileDown,
  Trash2,
  CheckCircle,
  Upload,
  Lock,
  ChevronsUpDown,
  X,
} from "lucide-react";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import {
  calculateSimulation,
  type ProposalContent,
  type SimulationInput,
  type SlideVersion,
} from "@/lib/proposals/simulation";
import {
  updateProposalContent,
  confirmProposal,
  overwriteProposal,
  deleteSlideVersion,
  unlockSlideForEdit,
  lockSlideAfterEdit,
} from "@/app/stp/proposal-actions";
import { JOB_TYPE_MAPPING, PREFECTURE_LOCATION_MAP } from "@/lib/proposals/simulation-config";

type ProposalData = {
  id: number;
  title: string;
  proposalNumber: string | null;
  status: string;
  filePath: string | null;
  fileName: string | null;
  externalUrl: string | null;
  externalService: string | null;
  isAutoGenerated: boolean;
  proposalContent: ProposalContent | null;
  createdAt: string;
  submissionId: number | null;
};

type Props = {
  proposal: ProposalData;
};

const salaryOptions = [
  { value: "市場平均より高い", label: "市場平均より高い" },
  { value: "平均±10%", label: "平均±10%" },
  { value: "平均-10〜20%", label: "平均-10〜20%" },
  { value: "平均-20%以上", label: "平均-20%以上" },
];

const jobTypeOptions = Object.keys(JOB_TYPE_MAPPING).map((key) => ({
  value: key,
  label: key,
}));

const prefectureOptions = Object.keys(PREFECTURE_LOCATION_MAP).map((key) => ({
  value: key,
  label: key,
}));

// CRM職種からGAS職種を逆引き
function findCrmJobType(gasJobType: string, gasIndustry: string): string {
  for (const [crmKey, mapping] of Object.entries(JOB_TYPE_MAPPING)) {
    if (mapping.jobType === gasJobType && mapping.industry === gasIndustry) {
      return crmKey;
    }
  }
  return "その他";
}

// GoogleスライドURLからembed URLに変換
function toEmbedUrl(slideUrl: string): string {
  return slideUrl.replace(/\/edit.*$/, "/embed?start=false&loop=false&delayms=3000");
}

// 万円表示用
function toMan(val: number): string {
  return Math.round(val / 10000).toLocaleString("ja-JP");
}

export function ProposalEditor({ proposal }: Props) {
  const router = useRouter();
  const [isGeneratingSlide, setIsGeneratingSlide] = useState(false);
  const [isConfirming, setIsConfirming] = useState(false);
  const [previewRefreshKey, setPreviewRefreshKey] = useState(0);

  // ダイアログ状態
  const [confirmDialogOpen, setConfirmDialogOpen] = useState(false);
  const [overwriteDialogOpen, setOverwriteDialogOpen] = useState(false);
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);

  // 初期コンテンツ
  const initialContent = proposal.proposalContent;
  const [content, setContent] = useState<ProposalContent | null>(initialContent);

  // スライドバージョン管理
  const slides = content?.slides || [];
  const activeSlides = slides.filter((s) => !s.deletedAt);
  const [selectedVersion, setSelectedVersion] = useState<number | null>(
    activeSlides.length > 0 ? activeSlides[activeSlides.length - 1].version : null,
  );

  const selectedSlide = slides.find((s) => s.version === selectedVersion);
  const isSelectedConfirmed = !!selectedSlide?.confirmedProposalId;

  const [input, setInput] = useState<SimulationInput>(() => {
    const base = initialContent?.input || {
      companyName: "",
      jobType: "営業",
      industry: "一般サービス業",
      location: "東京都",
      recruitmentAgencyCost: 0,
      jobAdCost: 0,
      referralCost: 0,
      otherCost: 0,
      annualHires: 24,
      targetHires: 12,
      salaryLevel: "平均±10%",
    };
    // 旧データ互換: locationsがなければlocationから生成
    if (!base.locations) {
      base.locations = base.location ? [base.location] : [];
    }
    return base;
  });

  // CRM職種選択状態
  const [selectedCrmJobType, setSelectedCrmJobType] = useState(
    initialContent ? findCrmJobType(initialContent.input.jobType, initialContent.input.industry) : "その他",
  );

  // 原本データ
  const originalInput = content?.originalInput;

  // スナップショットとの差分検出（フィールドハイライト用）
  const isFieldChanged = (field: keyof SimulationInput): boolean => {
    if (!selectedSlide?.inputSnapshot) return false;
    if (field === "jobType" || field === "industry") {
      // 職種カテゴリの比較: CRM職種で比較
      const snapshotCrmJobType = findCrmJobType(
        selectedSlide.inputSnapshot.jobType,
        selectedSlide.inputSnapshot.industry,
      );
      return selectedCrmJobType !== snapshotCrmJobType;
    }
    return input[field] !== selectedSlide.inputSnapshot[field];
  };

  const fieldHighlight = (field: keyof SimulationInput) =>
    isFieldChanged(field) ? "bg-amber-50 border-amber-300" : "";

  // 再計算が必要かどうか（input vs content.input）
  const calcFields: (keyof SimulationInput)[] = [
    "jobType", "industry", "location", "salaryLevel",
    "recruitmentAgencyCost", "jobAdCost", "referralCost", "otherCost",
    "annualHires", "targetHires",
  ];
  const needsRecalculation = content
    ? calcFields.some((f) => input[f] !== content.input[f])
    : false;

  // スライド再生成が必要かどうか
  const needsRegeneration = !selectedSlide || (
    selectedSlide?.inputSnapshot &&
    JSON.stringify(input) !== JSON.stringify(selectedSlide.inputSnapshot)
  );

  // バージョン切り替え時にinput/resultをスナップショットに反映
  const handleVersionChange = (version: number) => {
    setSelectedVersion(version);
    const slide = slides.find((s) => s.version === version);
    if (slide && slide.inputSnapshot) {
      const snapshot = { ...slide.inputSnapshot };
      // 旧データ互換: locationsがなければlocationから生成
      if (!snapshot.locations) {
        snapshot.locations = snapshot.location ? [snapshot.location] : [];
      }
      setInput(snapshot);
      setSelectedCrmJobType(
        findCrmJobType(slide.inputSnapshot.jobType, slide.inputSnapshot.industry),
      );
      // 計算結果もそのバージョンのスナップショットに切り替え
      setContent((prev) =>
        prev
          ? {
              ...prev,
              input: slide.inputSnapshot,
              result: slide.resultSnapshot,
            }
          : prev,
      );
    }
  };

  const handleInputChange = (field: keyof SimulationInput, value: string | number) => {
    setInput((prev) => ({ ...prev, [field]: value }));
  };

  const handleNumberChange = (field: keyof SimulationInput, value: string) => {
    const num = parseInt(value, 10);
    handleInputChange(field, isNaN(num) ? 0 : num);
  };

  const handleCrmJobTypeChange = (crmJobType: string) => {
    setSelectedCrmJobType(crmJobType);
    const mapping = JOB_TYPE_MAPPING[crmJobType];
    if (mapping) {
      setInput((prev) => ({
        ...prev,
        jobType: mapping.jobType,
        industry: mapping.industry,
      }));
    }
  };

  // 再計算（ローカルのみ）
  const handleRecalculate = () => {
    const result = calculateSimulation(input);
    const newContent: ProposalContent = {
      ...content!,
      input,
      result,
      generatedAt: new Date().toISOString(),
    };
    setContent(newContent);
    toast.success("再計算しました");
  };

  // スライド再生成（新バージョン作成）
  const handleGenerateSlide = async () => {
    if (!content) {
      toast.error("先に再計算を実行してください");
      return;
    }

    setIsGeneratingSlide(true);
    try {
      // まず最新の入力値でDB保存
      const result = calculateSimulation(input);
      const updatedContent: ProposalContent = {
        ...content,
        input,
        result,
        generatedAt: new Date().toISOString(),
      };
      const saveResult = await updateProposalContent(proposal.id, updatedContent);
      if (!saveResult.success) {
        toast.error(saveResult.error || "保存に失敗しました");
        return;
      }

      // スライド生成API呼び出し
      const res = await fetch(`/api/stp/proposals/${proposal.id}/slide`, {
        method: "POST",
      });

      if (res.ok) {
        const data = await res.json();
        // ローカルのcontentを更新（新バージョンを追加）
        const newSlide: SlideVersion = {
          version: data.version,
          slideFileId: data.fileId,
          slideUrl: data.slideUrl,
          embedUrl: data.embedUrl,
          createdAt: new Date().toISOString(),
          inputSnapshot: { ...input },
          resultSnapshot: result,
          confirmedProposalId: null,
          deletedAt: null,
          editUnlockedAt: null,
        };
        const newContent: ProposalContent = {
          ...updatedContent,
          result,
          slides: [...(updatedContent.slides || []), newSlide],
        };
        setContent(newContent);
        setSelectedVersion(data.version);
        toast.success(`スライド ver.${data.version} を生成しました`);
      } else {
        const data = await res.json().catch(() => ({}));
        toast.error(data.error || "スライド生成に失敗しました");
      }
    } catch {
      toast.error("スライド生成に失敗しました");
    } finally {
      setIsGeneratingSlide(false);
    }
  };

  // スライド編集（確定済みの場合はダイアログ）
  const handleSlideEdit = () => {
    if (!selectedSlide) return;

    if (isSelectedConfirmed) {
      setEditDialogOpen(true);
    } else {
      window.open(selectedSlide.slideUrl, "_blank");
    }
  };

  // 確定済みスライドの編集を許可
  const handleConfirmEdit = async () => {
    if (!selectedSlide) return;

    try {
      const result = await unlockSlideForEdit(proposal.id, selectedSlide.version);
      if (result.success) {
        // ローカルのcontentを更新
        const updatedSlides = (content?.slides || []).map((s) =>
          s.version === selectedSlide.version
            ? { ...s, editUnlockedAt: new Date().toISOString() }
            : s,
        );
        setContent((prev) => prev ? { ...prev, slides: updatedSlides } : prev);
        window.open(selectedSlide.slideUrl, "_blank");
        toast.success("スライドが編集可能になりました。編集後は「上書き」でPDFを更新してください");
      } else {
        toast.error(result.error || "編集解除に失敗しました");
      }
    } catch {
      toast.error("編集解除に失敗しました");
    }
    setEditDialogOpen(false);
  };

  // 権限を閲覧専用に戻す
  const handleLockSlide = async () => {
    if (!selectedSlide) return;
    try {
      const result = await lockSlideAfterEdit(proposal.id, selectedSlide.version);
      if (result.success) {
        // ローカルのcontentを更新
        const updatedSlides = (content?.slides || []).map((s) =>
          s.version === selectedSlide.version
            ? { ...s, editUnlockedAt: null }
            : s,
        );
        setContent((prev) => prev ? { ...prev, slides: updatedSlides } : prev);
        toast.success("スライド権限を閲覧専用に戻しました");
      } else {
        toast.error(result.error || "権限の変更に失敗しました");
      }
    } catch {
      toast.error("権限の変更に失敗しました");
    }
  };

  // 確定
  const handleConfirm = async () => {
    if (!selectedSlide) return;
    setIsConfirming(true);
    try {
      const result = await confirmProposal(proposal.id, selectedSlide.version);
      if (result.success && result.confirmedProposalId) {
        // ローカルのcontentを更新
        const updatedSlides = (content?.slides || []).map((s) =>
          s.version === selectedSlide.version
            ? { ...s, confirmedProposalId: result.confirmedProposalId! }
            : s,
        );
        setContent((prev) => prev ? { ...prev, slides: updatedSlides } : prev);
        toast.success(`ver.${selectedSlide.version} を確定しました`);
        router.refresh();
      } else {
        toast.error(result.error || "確定に失敗しました");
      }
    } catch {
      toast.error("確定に失敗しました");
    } finally {
      setIsConfirming(false);
      setConfirmDialogOpen(false);
    }
  };

  // 上書き
  const handleOverwrite = async () => {
    if (!selectedSlide) return;
    setIsConfirming(true);
    try {
      const result = await overwriteProposal(proposal.id, selectedSlide.version);
      if (result.success) {
        // ローカルのeditUnlockedAtもクリア（サーバー側でクリア済みだがstateに反映）
        const updatedSlides = (content?.slides || []).map((s) =>
          s.version === selectedSlide.version
            ? { ...s, editUnlockedAt: null }
            : s,
        );
        setContent((prev) => prev ? { ...prev, slides: updatedSlides } : prev);
        toast.success(`ver.${selectedSlide.version} を上書きしました`);
        router.refresh();
      } else {
        toast.error(result.error || "上書きに失敗しました");
      }
    } catch {
      toast.error("上書きに失敗しました");
    } finally {
      setIsConfirming(false);
      setOverwriteDialogOpen(false);
    }
  };

  // バージョン削除
  const handleDeleteVersion = async () => {
    if (!selectedSlide) return;
    try {
      const result = await deleteSlideVersion(proposal.id, selectedSlide.version);
      if (result.success) {
        // ローカルのcontentを更新
        const updatedSlides = (content?.slides || []).map((s) =>
          s.version === selectedSlide.version
            ? { ...s, deletedAt: new Date().toISOString(), confirmedProposalId: null }
            : s,
        );
        const newContent: ProposalContent = { ...content!, slides: updatedSlides };
        setContent(newContent);

        // 次のアクティブバージョンを選択
        const remainingActive = updatedSlides.filter((s) => !s.deletedAt);
        setSelectedVersion(
          remainingActive.length > 0
            ? remainingActive[remainingActive.length - 1].version
            : null,
        );
        toast.success(`ver.${selectedSlide.version} を削除しました`);
        router.refresh();
      } else {
        toast.error(result.error || "削除に失敗しました");
      }
    } catch {
      toast.error("削除に失敗しました");
    }
    setDeleteDialogOpen(false);
  };

  // PDF表示（オンザフライ）
  const handleViewPdf = () => {
    if (!selectedSlide) return;
    window.open(
      `/api/stp/proposals/${proposal.id}/pdf?slideFileId=${selectedSlide.slideFileId}`,
      "_blank",
    );
  };

  // 原本との差分表示用ヘルパー
  const renderOriginalHint = (field: keyof SimulationInput) => {
    if (!originalInput) return null;
    const original = originalInput[field];
    const current = input[field];
    if (original === current) return null;

    const displayValue = typeof original === "number"
      ? original.toLocaleString("ja-JP")
      : String(original);

    return (
      <span className="text-xs text-orange-500 ml-1">
        (原本: {displayValue})
      </span>
    );
  };

  return (
    <div>
      {/* ヘッダー */}
      <div className="border rounded-lg bg-white p-5 mb-8">
        <div className="flex items-center gap-4 mb-4">
          <Button variant="ghost" size="sm" onClick={() => router.back()}>
            <ArrowLeft className="h-4 w-4 mr-1" />
            戻る
          </Button>
          <div>
            <h1 className="text-xl font-bold">{proposal.title}</h1>
            <p className="text-sm text-gray-500">
              {proposal.proposalNumber && <span className="font-mono mr-2">{proposal.proposalNumber}</span>}
              {proposal.isAutoGenerated && <span className="text-xs bg-blue-100 text-blue-700 px-2 py-0.5 rounded">自動生成</span>}
            </p>
          </div>
        </div>
        <div className="border-t pt-4">
          {/* ボタン群 */}
          <div className="flex items-center gap-2 flex-wrap">
            <Button
              variant={needsRecalculation ? "default" : "outline"}
              size="sm"
              onClick={handleRecalculate}
              className={needsRecalculation ? "bg-amber-500 hover:bg-amber-600 text-white" : ""}
            >
              <RefreshCw className="h-4 w-4 mr-1" />
              再計算
            </Button>
            <Button
              size="sm"
              onClick={handleGenerateSlide}
              disabled={isGeneratingSlide || !content}
              className={needsRegeneration && !isGeneratingSlide
                ? "bg-blue-600 hover:bg-blue-700 text-white"
                : ""
              }
              variant={needsRegeneration && !isGeneratingSlide ? "default" : "secondary"}
            >
              {isGeneratingSlide ? (
                <Loader2 className="h-4 w-4 mr-1 animate-spin" />
              ) : (
                <Presentation className="h-4 w-4 mr-1" />
              )}
              {isGeneratingSlide ? "生成中..." : "スライド再生成"}
            </Button>
            {selectedSlide && !selectedSlide.deletedAt && (
              <>
                <div className="w-px h-6 bg-gray-300" />
                {isSelectedConfirmed && selectedSlide.editUnlockedAt && (
                  <span className="text-xs bg-yellow-100 text-yellow-700 px-2 py-0.5 rounded">
                    編集中
                  </span>
                )}
                <Button variant="outline" size="sm" onClick={handleSlideEdit}>
                  <ExternalLink className="h-4 w-4 mr-1" />
                  スライド編集
                </Button>
                {isSelectedConfirmed && selectedSlide.editUnlockedAt && (
                  <Button variant="outline" size="sm" onClick={handleLockSlide}>
                    <Lock className="h-4 w-4 mr-1" />
                    権限を戻す
                  </Button>
                )}
                <Button variant="outline" size="sm" onClick={handleViewPdf}>
                  <FileDown className="h-4 w-4 mr-1" />
                  PDF表示
                </Button>
                <div className="w-px h-6 bg-gray-300" />
                {isSelectedConfirmed ? (
                  <Button
                    size="sm"
                    onClick={() => setOverwriteDialogOpen(true)}
                    disabled={isConfirming}
                    className="bg-orange-600 hover:bg-orange-700"
                  >
                    {isConfirming ? (
                      <Loader2 className="h-4 w-4 mr-1 animate-spin" />
                    ) : (
                      <Upload className="h-4 w-4 mr-1" />
                    )}
                    上書き
                  </Button>
                ) : (
                  <Button
                    size="sm"
                    onClick={() => setConfirmDialogOpen(true)}
                    disabled={isConfirming}
                    className="bg-green-600 hover:bg-green-700"
                  >
                    {isConfirming ? (
                      <Loader2 className="h-4 w-4 mr-1 animate-spin" />
                    ) : (
                      <CheckCircle className="h-4 w-4 mr-1" />
                    )}
                    確定
                  </Button>
                )}
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-8 w-8"
                  onClick={() => setDeleteDialogOpen(true)}
                  title="このバージョンを削除"
                >
                  <Trash2 className="h-4 w-4 text-red-500" />
                </Button>
              </>
            )}
          </div>
        </div>
      </div>

      {/* 2カラムレイアウト */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* 左パネル: 入力フォーム */}
        <div className="space-y-6">
          {/* 基本情報 */}
          <div className="border rounded-lg p-4 space-y-4">
            <h3 className="font-semibold border-b pb-2">基本情報</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="col-span-2 space-y-1">
                <Label>
                  会社名
                  {renderOriginalHint("companyName")}
                </Label>
                <Input
                  value={input.companyName}
                  onChange={(e) => handleInputChange("companyName", e.target.value)}
                  className={fieldHighlight("companyName")}
                />
              </div>
              <div className="space-y-1 min-w-0">
                <Label>職種カテゴリ</Label>
                <Select value={selectedCrmJobType} onValueChange={handleCrmJobTypeChange}>
                  <SelectTrigger className={`w-full [&>span]:truncate ${fieldHighlight("jobType")}`}>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent position="popper" className="z-50 max-h-[300px]">
                    {jobTypeOptions.map((opt) => (
                      <SelectItem key={opt.value} value={opt.value}>
                        {opt.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1 min-w-0">
                <Label>
                  勤務地
                  {renderOriginalHint("location")}
                </Label>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button
                      variant="outline"
                      role="combobox"
                      className={`w-full justify-between font-normal ${fieldHighlight("location")}`}
                    >
                      {(input.locations?.length || 0) > 0
                        ? `${input.locations!.length}件選択中`
                        : "都道府県を選択"}
                      <ChevronsUpDown className="ml-2 h-4 w-4 shrink-0 opacity-50" />
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-full p-0" align="start">
                    <div className="max-h-[300px] overflow-y-auto p-2">
                      {prefectureOptions.map((opt) => (
                        <label
                          key={opt.value}
                          className="flex items-center gap-2 px-2 py-1.5 hover:bg-gray-100 rounded cursor-pointer text-sm"
                        >
                          <Checkbox
                            checked={input.locations?.includes(opt.value) || false}
                            onCheckedChange={(checked) => {
                              const newLocations = checked
                                ? [...(input.locations || []), opt.value]
                                : (input.locations || []).filter((l) => l !== opt.value);
                              setInput((prev) => ({
                                ...prev,
                                locations: newLocations,
                                location: newLocations[0] || "",
                              }));
                            }}
                          />
                          {opt.label}
                        </label>
                      ))}
                    </div>
                  </PopoverContent>
                </Popover>
                {(input.locations?.length || 0) > 0 && (
                  <div className="flex flex-wrap gap-1 mt-1">
                    {input.locations!.map((loc) => (
                      <Badge key={loc} variant="secondary" className="text-xs">
                        {loc}
                        <button
                          type="button"
                          className="ml-1 hover:text-red-500"
                          onClick={() => {
                            const newLocations = input.locations!.filter((l) => l !== loc);
                            setInput((prev) => ({
                              ...prev,
                              locations: newLocations,
                              location: newLocations[0] || "",
                            }));
                          }}
                        >
                          <X className="h-3 w-3" />
                        </button>
                      </Badge>
                    ))}
                  </div>
                )}
              </div>
              <div className="space-y-1">
                <Label>給与水準</Label>
                <Select value={input.salaryLevel} onValueChange={(v) => handleInputChange("salaryLevel", v)}>
                  <SelectTrigger className={fieldHighlight("salaryLevel")}>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {salaryOptions.map((opt) => (
                      <SelectItem key={opt.value} value={opt.value}>
                        {opt.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1">
                <Label>判定: 職種</Label>
                <Input value={input.jobType} readOnly className="bg-gray-50" />
              </div>
              <div className="space-y-1">
                <Label>判定: 業界</Label>
                <Input value={input.industry} readOnly className="bg-gray-50" />
              </div>
            </div>
          </div>

          {/* コスト情報 */}
          <div className="border rounded-lg p-4 space-y-4">
            <h3 className="font-semibold border-b pb-2">過去の採用コスト（年間）</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <Label>
                  人材紹介費用（円）
                  {renderOriginalHint("recruitmentAgencyCost")}
                </Label>
                <Input
                  type="number"
                  value={input.recruitmentAgencyCost || ""}
                  onChange={(e) => handleNumberChange("recruitmentAgencyCost", e.target.value)}
                  placeholder="0"
                  className={fieldHighlight("recruitmentAgencyCost")}
                />
              </div>
              <div className="space-y-1">
                <Label>
                  求人広告費用（円）
                  {renderOriginalHint("jobAdCost")}
                </Label>
                <Input
                  type="number"
                  value={input.jobAdCost || ""}
                  onChange={(e) => handleNumberChange("jobAdCost", e.target.value)}
                  placeholder="0"
                  className={fieldHighlight("jobAdCost")}
                />
              </div>
              <div className="space-y-1">
                <Label>
                  リファラル費用（円）
                  {renderOriginalHint("referralCost")}
                </Label>
                <Input
                  type="number"
                  value={input.referralCost || ""}
                  onChange={(e) => handleNumberChange("referralCost", e.target.value)}
                  placeholder="0"
                  className={fieldHighlight("referralCost")}
                />
              </div>
              <div className="space-y-1">
                <Label>
                  その他費用（円）
                  {renderOriginalHint("otherCost")}
                </Label>
                <Input
                  type="number"
                  value={input.otherCost || ""}
                  onChange={(e) => handleNumberChange("otherCost", e.target.value)}
                  placeholder="0"
                  className={fieldHighlight("otherCost")}
                />
              </div>
            </div>
          </div>

          {/* 採用人数 */}
          <div className="border rounded-lg p-4 space-y-4">
            <h3 className="font-semibold border-b pb-2">採用人数</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <Label>
                  過去の年間採用人数
                  {renderOriginalHint("annualHires")}
                </Label>
                <Input
                  type="number"
                  value={input.annualHires || ""}
                  onChange={(e) => handleNumberChange("annualHires", e.target.value)}
                  placeholder="24"
                  className={fieldHighlight("annualHires")}
                />
              </div>
              <div className="space-y-1">
                <Label>
                  目標採用人数
                  {renderOriginalHint("targetHires")}
                </Label>
                <Input
                  type="number"
                  value={input.targetHires || ""}
                  onChange={(e) => handleNumberChange("targetHires", e.target.value)}
                  placeholder="12"
                  className={fieldHighlight("targetHires")}
                />
              </div>
            </div>
          </div>

          {/* 係数表示 */}
          {content && (
            <div className="border rounded-lg p-4 space-y-2 bg-gray-50">
              <h3 className="font-semibold border-b pb-2 text-sm">計算係数</h3>
              <div className="grid grid-cols-3 gap-2 text-xs">
                <div>業界: <span className="font-mono font-bold">{content.result.coefficients.industry}</span></div>
                <div>職種: <span className="font-mono font-bold">{content.result.coefficients.job}</span></div>
                <div>給与: <span className="font-mono font-bold">{content.result.coefficients.salary}</span></div>
                <div>勤務地: <span className="font-mono font-bold">{content.result.coefficients.location}</span></div>
                <div>人数: <span className="font-mono font-bold">{content.result.coefficients.headcount}</span></div>
                <div>合計: <span className="font-mono font-bold text-blue-600">{content.result.coefficients.total.toFixed(4)}</span></div>
              </div>
            </div>
          )}

          {/* 計算結果サマリー */}
          {content && (
            <div className="border rounded-lg p-4 space-y-3">
              <h3 className="font-semibold border-b pb-2 text-sm">計算結果</h3>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <div className="text-gray-500 mb-1">現状（Before）</div>
                  <div>年間採用コスト: <span className="font-bold">{toMan(content.result.before.annualCost)}</span> 万円</div>
                  <div>採用単価: <span className="font-bold">{toMan(content.result.before.costPerHire)}</span> 万円</div>
                  <div>目標人数でのコスト: <span className="font-bold">{toMan(content.result.before.totalCostForTarget)}</span> 万円</div>
                </div>
                <div>
                  <div className="text-gray-500 mb-1">成果報酬型 (10%)</div>
                  <div>合計コスト: <span className="font-bold">{toMan(content.result.scenario10.successFeeCost)}</span> 万円</div>
                  <div>削減率: <span className="font-bold text-green-600">{content.result.scenario10.reductionSuccess}%</span></div>
                  <div>予想期間: <span className="font-bold">{content.result.scenario10.months}</span> ヶ月</div>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* 右パネル: Googleスライドプレビュー */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <h3 className="font-semibold">プレビュー</h3>
            {slides.length > 0 && (
              <div className="flex items-center gap-2">
                {isSelectedConfirmed && (
                  <span className="text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded">
                    確定済み
                  </span>
                )}
                <Select
                  value={selectedVersion?.toString() || ""}
                  onValueChange={(v) => handleVersionChange(parseInt(v, 10))}
                >
                  <SelectTrigger className="w-[180px] h-8 text-sm">
                    <SelectValue placeholder="バージョン" />
                  </SelectTrigger>
                  <SelectContent position="popper" className="z-50">
                    {slides.map((s) => {
                      const isDeleted = !!s.deletedAt;
                      const isConfirmed = !!s.confirmedProposalId;
                      return (
                        <SelectItem
                          key={s.version}
                          value={s.version.toString()}
                          disabled={isDeleted}
                          className={isDeleted ? "text-gray-400" : ""}
                        >
                          ver.{s.version}
                          {isConfirmed && " (確定済み)"}
                          {isDeleted && " (削除済み)"}
                        </SelectItem>
                      );
                    })}
                  </SelectContent>
                </Select>
              </div>
            )}
          </div>
          {selectedSlide && !selectedSlide.deletedAt ? (
            <div className="border rounded-lg overflow-hidden bg-gray-100">
              <iframe
                key={`${selectedSlide.version}-${previewRefreshKey}`}
                src={`${toEmbedUrl(selectedSlide.slideUrl)}&_t=${previewRefreshKey}`}
                width="100%"
                height="569"
                allowFullScreen
                className="border-0"
                title={`提案書プレビュー ver.${selectedSlide.version}`}
              />
              <div className="px-4 py-2 bg-white border-t flex items-center justify-between text-sm text-gray-500">
                <span>
                  ver.{selectedSlide.version}
                  {isSelectedConfirmed
                    ? " - 確定済み（閲覧専用）"
                    : " - Googleスライドで直接編集できます"
                  }
                </span>
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-7 px-2 text-xs text-gray-500"
                  onClick={() => setPreviewRefreshKey((k) => k + 1)}
                >
                  <RefreshCw className="h-3 w-3 mr-1" />
                  プレビュー更新
                </Button>
              </div>
            </div>
          ) : (
            <div className="border rounded-lg p-8 text-center text-gray-500 min-h-[400px] flex flex-col items-center justify-center gap-4">
              <Presentation className="h-12 w-12 text-gray-300" />
              <div>
                <p className="font-medium">スライドが未生成です</p>
                <p className="text-sm mt-1">
                  入力値を確認して「スライド再生成」ボタンを押してください
                </p>
              </div>
              <div className="text-xs text-gray-400 mt-2 space-y-1">
                <p>1. 入力値を編集 → 「再計算」で確認</p>
                <p>2. 「スライド再生成」でGoogleスライドを作成</p>
                <p>3. Googleスライドで直接編集可能</p>
                <p>4. 「確定」で提案書管理に登録</p>
              </div>
            </div>
          )}

          {/* バージョン切り替え時の説明 */}
          {selectedSlide && !selectedSlide.deletedAt && (
            <p className="mt-2 text-xs text-gray-400 text-center">
              ver.{selectedSlide.version} のデータを表示中。左パネルで値を変更し「スライド再生成」で新バージョンを作成できます。
            </p>
          )}
        </div>
      </div>

      {/* 確定ダイアログ */}
      <AlertDialog open={confirmDialogOpen} onOpenChange={setConfirmDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>提案書を確定しますか？</AlertDialogTitle>
            <AlertDialogDescription>
              ver.{selectedSlide?.version} を提案書管理に登録します。
              PDFが生成され、スライドは閲覧専用になります。
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>キャンセル</AlertDialogCancel>
            <AlertDialogAction onClick={handleConfirm} className="bg-green-600 hover:bg-green-700">
              確定する
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* 上書きダイアログ */}
      <AlertDialog open={overwriteDialogOpen} onOpenChange={setOverwriteDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>提案書を上書きしますか？</AlertDialogTitle>
            <AlertDialogDescription>
              ver.{selectedSlide?.version} の提案書管理エントリを上書き更新します。
              PDFが再生成され、スライドは閲覧専用に戻ります。
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>キャンセル</AlertDialogCancel>
            <AlertDialogAction onClick={handleOverwrite} className="bg-orange-600 hover:bg-orange-700">
              上書きする
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* スライド編集ダイアログ（確定済み） */}
      <AlertDialog open={editDialogOpen} onOpenChange={setEditDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>確定済みスライドを編集しますか？</AlertDialogTitle>
            <AlertDialogDescription>
              このバージョンは提案書として確定済みです。
              スライドを編集しますか？
              編集後は「上書き」で提案書を更新できます。
              新しいバージョンとして作成したい場合は「スライド再生成」を使用してください。
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>キャンセル</AlertDialogCancel>
            <AlertDialogAction onClick={handleConfirmEdit}>
              編集する
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* 削除ダイアログ */}
      <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>
              ver.{selectedSlide?.version} を削除しますか？
            </AlertDialogTitle>
            <AlertDialogDescription>
              {isSelectedConfirmed
                ? "このバージョンは提案書管理に確定済みです。削除すると提案書管理のエントリも削除されます。よろしいですか？"
                : "このバージョンを削除します。削除後は元に戻せません。"
              }
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>キャンセル</AlertDialogCancel>
            <AlertDialogAction onClick={handleDeleteVersion} className="bg-red-600 hover:bg-red-700">
              削除する
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
