"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { toast } from "sonner";
import { ArrowLeft, RefreshCw, Save, FileDown, ExternalLink, Presentation, Loader2 } from "lucide-react";
import { calculateSimulation, type ProposalContent, type SimulationInput } from "@/lib/proposals/simulation";
import { regenerateProposal } from "@/app/stp/proposal-actions";
import { JOB_TYPE_MAPPING, PREFECTURE_LOCATION_MAP } from "@/lib/proposals/simulation-config";

type ProposalData = {
  id: number;
  title: string;
  proposalNumber: string | null;
  status: string;
  filePath: string | null;
  fileName: string | null;
  externalUrl: string | null;
  externalService: string | null;
  isAutoGenerated: boolean;
  proposalContent: ProposalContent | null;
  createdAt: string;
};

type Props = {
  proposal: ProposalData;
};

const salaryOptions = [
  { value: "市場平均より高い", label: "市場平均より高い" },
  { value: "平均±10%", label: "平均±10%" },
  { value: "平均-10〜20%", label: "平均-10〜20%" },
  { value: "平均-20%以上", label: "平均-20%以上" },
];

const jobTypeOptions = Object.keys(JOB_TYPE_MAPPING).map((key) => ({
  value: key,
  label: key,
}));

const prefectureOptions = Object.keys(PREFECTURE_LOCATION_MAP).map((key) => ({
  value: key,
  label: key,
}));

// CRM職種からGAS職種を逆引き
function findCrmJobType(gasJobType: string, gasIndustry: string): string {
  for (const [crmKey, mapping] of Object.entries(JOB_TYPE_MAPPING)) {
    if (mapping.jobType === gasJobType && mapping.industry === gasIndustry) {
      return crmKey;
    }
  }
  return "その他";
}

// GoogleスライドURLからembed URLに変換
function toEmbedUrl(slideUrl: string): string {
  // https://docs.google.com/presentation/d/{ID}/edit → /embed?...
  return slideUrl.replace(/\/edit.*$/, "/embed?start=false&loop=false&delayms=3000");
}

export function ProposalEditor({ proposal }: Props) {
  const router = useRouter();
  const [isSaving, setIsSaving] = useState(false);
  const [isGeneratingSlide, setIsGeneratingSlide] = useState(false);
  const [isSavingPdf, setIsSavingPdf] = useState(false);

  // Googleスライド・PDF状態
  const [slideUrl, setSlideUrl] = useState<string | null>(proposal.externalUrl);
  const [pdfPath, setPdfPath] = useState<string | null>(proposal.filePath);

  // 初期コンテンツ
  const initialContent = proposal.proposalContent;

  const [input, setInput] = useState<SimulationInput>(
    initialContent?.input || {
      companyName: "",
      jobType: "営業",
      industry: "一般サービス業",
      location: "東京都",
      recruitmentAgencyCost: 0,
      jobAdCost: 0,
      referralCost: 0,
      otherCost: 0,
      annualHires: 24,
      targetHires: 12,
      salaryLevel: "平均±10%",
    },
  );

  const [content, setContent] = useState<ProposalContent | null>(initialContent);

  // CRM職種選択状態（GAS職種/業界との連携用）
  const [selectedCrmJobType, setSelectedCrmJobType] = useState(
    initialContent ? findCrmJobType(initialContent.input.jobType, initialContent.input.industry) : "その他",
  );

  const handleInputChange = (field: keyof SimulationInput, value: string | number) => {
    setInput((prev) => ({ ...prev, [field]: value }));
  };

  const handleNumberChange = (field: keyof SimulationInput, value: string) => {
    const num = parseInt(value, 10);
    handleInputChange(field, isNaN(num) ? 0 : num);
  };

  const handleCrmJobTypeChange = (crmJobType: string) => {
    setSelectedCrmJobType(crmJobType);
    const mapping = JOB_TYPE_MAPPING[crmJobType];
    if (mapping) {
      setInput((prev) => ({
        ...prev,
        jobType: mapping.jobType,
        industry: mapping.industry,
      }));
    }
  };

  const handleRecalculate = () => {
    const result = calculateSimulation(input);
    const newContent: ProposalContent = {
      input,
      result,
      generatedAt: new Date().toISOString(),
      version: 1,
    };
    setContent(newContent);
    toast.success("再計算しました");
  };

  // 計算結果をDBに保存
  const handleSave = async () => {
    if (!content) {
      toast.error("先に再計算を実行してください");
      return;
    }

    setIsSaving(true);
    try {
      const result = await regenerateProposal(proposal.id, input);
      if (result.success && result.content) {
        setContent(result.content);
        toast.success("保存しました");
      } else {
        toast.error(result.error || "保存に失敗しました");
      }
    } catch {
      toast.error("保存に失敗しました");
    } finally {
      setIsSaving(false);
    }
  };

  // Googleスライド生成（テンプレートコピー → 置換）
  const handleGenerateSlide = async () => {
    if (!content) {
      toast.error("先に保存してください");
      return;
    }

    setIsGeneratingSlide(true);
    try {
      // まず最新の入力値でDBを更新
      const saveResult = await regenerateProposal(proposal.id, input);
      if (!saveResult.success) {
        toast.error(saveResult.error || "保存に失敗しました");
        return;
      }
      if (saveResult.content) {
        setContent(saveResult.content);
      }

      // スライド生成API呼び出し
      const res = await fetch(`/api/stp/proposals/${proposal.id}/slide`, {
        method: "POST",
      });

      if (res.ok) {
        const data = await res.json();
        setSlideUrl(data.slideUrl);
        toast.success("Googleスライドを生成しました");
      } else {
        const data = await res.json().catch(() => ({}));
        toast.error(data.error || "スライド生成に失敗しました");
      }
    } catch {
      toast.error("スライド生成に失敗しました");
    } finally {
      setIsGeneratingSlide(false);
    }
  };

  // PDF保存（GoogleスライドからエクスポートしてCRMに保存）
  const handleSavePdf = async () => {
    if (!slideUrl) {
      toast.error("先にGoogleスライドを生成してください");
      return;
    }

    setIsSavingPdf(true);
    try {
      const res = await fetch(`/api/stp/proposals/${proposal.id}/pdf`, {
        method: "POST",
      });

      if (res.ok) {
        const data = await res.json();
        setPdfPath(data.filePath);
        toast.success("PDFを保存しました");
        router.refresh();
      } else {
        const data = await res.json().catch(() => ({}));
        toast.error(data.error || "PDF保存に失敗しました");
      }
    } catch {
      toast.error("PDF保存に失敗しました");
    } finally {
      setIsSavingPdf(false);
    }
  };

  return (
    <div>
      {/* ヘッダー */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="sm" onClick={() => router.back()}>
            <ArrowLeft className="h-4 w-4 mr-1" />
            戻る
          </Button>
          <div>
            <h1 className="text-xl font-bold">{proposal.title}</h1>
            <p className="text-sm text-gray-500">
              {proposal.proposalNumber && <span className="font-mono mr-2">{proposal.proposalNumber}</span>}
              {proposal.isAutoGenerated && <span className="text-xs bg-blue-100 text-blue-700 px-2 py-0.5 rounded">自動生成</span>}
            </p>
          </div>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={handleRecalculate}>
            <RefreshCw className="h-4 w-4 mr-1" />
            再計算
          </Button>
          <Button onClick={handleSave} disabled={isSaving}>
            <Save className="h-4 w-4 mr-1" />
            {isSaving ? "保存中..." : "保存"}
          </Button>
          <Button
            variant="secondary"
            onClick={handleGenerateSlide}
            disabled={isGeneratingSlide || !content}
          >
            {isGeneratingSlide ? (
              <Loader2 className="h-4 w-4 mr-1 animate-spin" />
            ) : (
              <Presentation className="h-4 w-4 mr-1" />
            )}
            {isGeneratingSlide ? "生成中..." : "スライド生成"}
          </Button>
          {slideUrl && (
            <>
              <Button variant="outline" asChild>
                <a href={slideUrl} target="_blank" rel="noopener noreferrer">
                  <ExternalLink className="h-4 w-4 mr-1" />
                  スライド編集
                </a>
              </Button>
              <Button
                variant="secondary"
                onClick={handleSavePdf}
                disabled={isSavingPdf}
              >
                {isSavingPdf ? (
                  <Loader2 className="h-4 w-4 mr-1 animate-spin" />
                ) : (
                  <FileDown className="h-4 w-4 mr-1" />
                )}
                {isSavingPdf ? "保存中..." : "PDF保存"}
              </Button>
            </>
          )}
          {pdfPath && (
            <Button variant="outline" asChild>
              <a href={`/api/stp/proposals/${proposal.id}/pdf`} target="_blank" rel="noopener noreferrer">
                <FileDown className="h-4 w-4 mr-1" />
                PDF表示
              </a>
            </Button>
          )}
        </div>
      </div>

      {/* 2カラムレイアウト */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* 左パネル: 入力フォーム */}
        <div className="space-y-6">
          {/* 基本情報 */}
          <div className="border rounded-lg p-4 space-y-4">
            <h3 className="font-semibold border-b pb-2">基本情報</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="col-span-2 space-y-1">
                <Label>会社名</Label>
                <Input
                  value={input.companyName}
                  onChange={(e) => handleInputChange("companyName", e.target.value)}
                />
              </div>
              <div className="space-y-1">
                <Label>職種カテゴリ</Label>
                <Select value={selectedCrmJobType} onValueChange={handleCrmJobTypeChange}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {jobTypeOptions.map((opt) => (
                      <SelectItem key={opt.value} value={opt.value}>
                        {opt.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1">
                <Label>勤務地</Label>
                <Select value={input.location} onValueChange={(v) => handleInputChange("location", v)}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {prefectureOptions.map((opt) => (
                      <SelectItem key={opt.value} value={opt.value}>
                        {opt.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1">
                <Label>給与水準</Label>
                <Select value={input.salaryLevel} onValueChange={(v) => handleInputChange("salaryLevel", v)}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {salaryOptions.map((opt) => (
                      <SelectItem key={opt.value} value={opt.value}>
                        {opt.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-1">
                <Label>判定: 職種</Label>
                <Input value={input.jobType} readOnly className="bg-gray-50" />
              </div>
              <div className="space-y-1">
                <Label>判定: 業界</Label>
                <Input value={input.industry} readOnly className="bg-gray-50" />
              </div>
            </div>
          </div>

          {/* コスト情報 */}
          <div className="border rounded-lg p-4 space-y-4">
            <h3 className="font-semibold border-b pb-2">過去の採用コスト（年間）</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <Label>人材紹介費用（円）</Label>
                <Input
                  type="number"
                  value={input.recruitmentAgencyCost || ""}
                  onChange={(e) => handleNumberChange("recruitmentAgencyCost", e.target.value)}
                  placeholder="0"
                />
              </div>
              <div className="space-y-1">
                <Label>求人広告費用（円）</Label>
                <Input
                  type="number"
                  value={input.jobAdCost || ""}
                  onChange={(e) => handleNumberChange("jobAdCost", e.target.value)}
                  placeholder="0"
                />
              </div>
              <div className="space-y-1">
                <Label>リファラル費用（円）</Label>
                <Input
                  type="number"
                  value={input.referralCost || ""}
                  onChange={(e) => handleNumberChange("referralCost", e.target.value)}
                  placeholder="0"
                />
              </div>
              <div className="space-y-1">
                <Label>その他費用（円）</Label>
                <Input
                  type="number"
                  value={input.otherCost || ""}
                  onChange={(e) => handleNumberChange("otherCost", e.target.value)}
                  placeholder="0"
                />
              </div>
            </div>
          </div>

          {/* 採用人数 */}
          <div className="border rounded-lg p-4 space-y-4">
            <h3 className="font-semibold border-b pb-2">採用人数</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <Label>過去の年間採用人数</Label>
                <Input
                  type="number"
                  value={input.annualHires || ""}
                  onChange={(e) => handleNumberChange("annualHires", e.target.value)}
                  placeholder="24"
                />
              </div>
              <div className="space-y-1">
                <Label>目標採用人数</Label>
                <Input
                  type="number"
                  value={input.targetHires || ""}
                  onChange={(e) => handleNumberChange("targetHires", e.target.value)}
                  placeholder="12"
                />
              </div>
            </div>
          </div>

          {/* 係数表示（読み取り専用） */}
          {content && (
            <div className="border rounded-lg p-4 space-y-2 bg-gray-50">
              <h3 className="font-semibold border-b pb-2 text-sm">計算係数</h3>
              <div className="grid grid-cols-3 gap-2 text-xs">
                <div>業界: <span className="font-mono font-bold">{content.result.coefficients.industry}</span></div>
                <div>職種: <span className="font-mono font-bold">{content.result.coefficients.job}</span></div>
                <div>給与: <span className="font-mono font-bold">{content.result.coefficients.salary}</span></div>
                <div>勤務地: <span className="font-mono font-bold">{content.result.coefficients.location}</span></div>
                <div>人数: <span className="font-mono font-bold">{content.result.coefficients.headcount}</span></div>
                <div>合計: <span className="font-mono font-bold text-blue-600">{content.result.coefficients.total.toFixed(4)}</span></div>
              </div>
            </div>
          )}
        </div>

        {/* 右パネル: Googleスライドプレビュー */}
        <div>
          <h3 className="font-semibold mb-2">プレビュー</h3>
          {slideUrl ? (
            <div className="border rounded-lg overflow-hidden bg-gray-100">
              <iframe
                src={toEmbedUrl(slideUrl)}
                width="100%"
                height="569"
                allowFullScreen
                className="border-0"
                title="提案書プレビュー"
              />
              <div className="px-4 py-2 bg-white border-t flex items-center justify-between text-sm text-gray-500">
                <span>Googleスライドで直接編集できます</span>
                <a
                  href={slideUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 hover:underline flex items-center gap-1"
                >
                  <ExternalLink className="h-3 w-3" />
                  編集する
                </a>
              </div>
            </div>
          ) : (
            <div className="border rounded-lg p-8 text-center text-gray-500 min-h-[400px] flex flex-col items-center justify-center gap-4">
              <Presentation className="h-12 w-12 text-gray-300" />
              <div>
                <p className="font-medium">スライドが未生成です</p>
                <p className="text-sm mt-1">
                  入力値を確認して「スライド生成」ボタンを押してください
                </p>
              </div>
              <div className="text-xs text-gray-400 mt-2 space-y-1">
                <p>1. 入力値を編集 → 「再計算」で確認</p>
                <p>2. 「保存」でデータを保存</p>
                <p>3. 「スライド生成」でGoogleスライドを作成</p>
                <p>4. Googleスライドで直接編集可能</p>
                <p>5. 「PDF保存」でCRMにPDFを保存</p>
              </div>
            </div>
          )}

          {/* PDF保存済み表示 */}
          {pdfPath && (
            <div className="mt-4 border rounded-lg p-4 bg-green-50 flex items-center justify-between">
              <div className="flex items-center gap-2 text-green-700">
                <FileDown className="h-5 w-5" />
                <span className="text-sm font-medium">PDFが保存済みです</span>
              </div>
              <Button variant="outline" size="sm" asChild>
                <a href={`/api/stp/proposals/${proposal.id}/pdf`} target="_blank" rel="noopener noreferrer">
                  PDFを表示
                </a>
              </Button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
