"use server";

import { prisma } from "@/lib/prisma";

export type TransactionListItem = {
  id: number;
  type: string;
  counterpartyId: number;
  counterpartyName: string;
  expenseCategoryId: number;
  expenseCategoryName: string;
  costCenterName: string | null;
  allocationTemplateName: string | null;
  amount: number;
  taxAmount: number;
  taxRate: number;
  taxType: string;
  periodFrom: string;
  periodTo: string;
  paymentDueDate: string | null;
  status: string;
  note: string | null;
  isAutoGenerated: boolean;
  sourceType: string | null;
  invoiceGroupId: number | null;
  paymentGroupId: number | null;
  contractId: number | null;
  createdByName: string;
  createdAt: string;
  updatedAt: string;
};

export type TransactionFilters = {
  type?: "revenue" | "expense";
  status?: string;
  counterpartyId?: number;
  periodFrom?: string;
  periodTo?: string;
};

export type TransactionSort = {
  field: string;
  direction: "asc" | "desc";
};

/** サーバーサイドページネーション導入時に使用予定 */
export async function listTransactions(
  filters?: TransactionFilters,
  sort?: TransactionSort
): Promise<TransactionListItem[]> {
  const where: Record<string, unknown> = {
    deletedAt: null,
    // STPプロジェクトの取引のみ（projectId=1 or projectId=null で STP関連）
    // 将来的にはプロジェクトIDで絞り込む
  };

  if (filters?.type) {
    where.type = filters.type;
  }
  if (filters?.status) {
    where.status = filters.status;
  }
  if (filters?.counterpartyId) {
    where.counterpartyId = filters.counterpartyId;
  }
  if (filters?.periodFrom) {
    where.periodFrom = { gte: new Date(filters.periodFrom) };
  }
  if (filters?.periodTo) {
    where.periodTo = { lte: new Date(filters.periodTo) };
  }

  const orderBy: Record<string, string>[] = [];
  if (sort?.field) {
    orderBy.push({ [sort.field]: sort.direction });
  } else {
    orderBy.push({ periodFrom: "desc" }, { id: "desc" });
  }

  const records = await prisma.transaction.findMany({
    where,
    include: {
      counterparty: true,
      expenseCategory: true,
      costCenter: true,
      allocationTemplate: true,
      creator: true,
    },
    orderBy,
  });

  return records.map((r) => ({
    id: r.id,
    type: r.type,
    counterpartyId: r.counterpartyId,
    counterpartyName: r.counterparty.name,
    expenseCategoryId: r.expenseCategoryId,
    expenseCategoryName: r.expenseCategory.name,
    costCenterName: r.costCenter?.name ?? null,
    allocationTemplateName: r.allocationTemplate?.name ?? null,
    amount: r.amount,
    taxAmount: r.taxAmount,
    taxRate: r.taxRate,
    taxType: r.taxType,
    periodFrom: r.periodFrom.toISOString().split("T")[0],
    periodTo: r.periodTo.toISOString().split("T")[0],
    paymentDueDate: r.paymentDueDate
      ? r.paymentDueDate.toISOString().split("T")[0]
      : null,
    status: r.status,
    note: r.note,
    isAutoGenerated: r.isAutoGenerated,
    sourceType: r.sourceType,
    invoiceGroupId: r.invoiceGroupId,
    paymentGroupId: r.paymentGroupId,
    contractId: r.contractId,
    createdByName: r.creator.name,
    createdAt: r.createdAt.toISOString().split("T")[0],
    updatedAt: r.updatedAt.toISOString().split("T")[0],
  }));
}
