"use server";

import { prisma } from "@/lib/prisma";
import { requireEdit, getSession } from "@/lib/auth";
import { hasPermission, isFounder, isSystemAdmin } from "@/lib/auth";
import { recordChangeLog } from "@/app/accounting/changelog/actions";
import type { UserPermission, SessionUser } from "@/types/auth";
import { revalidatePath } from "next/cache";
import { toLocalDateString } from "@/lib/utils";
import type {
  AllocationGroupItemSummary,
  TransactionListItem,
  TransactionFilters,
  TransactionSort,
} from "./types";

// ============================================
// 機密フィルタヘルパー
// ============================================

function buildConfidentialFilter(user: SessionUser) {
  if (isSystemAdmin(user) || isFounder(user)) return {};
  if (hasPermission(user.permissions, "accounting", "edit")) return {};
  return { OR: [{ isConfidential: false }, { isConfidential: true, createdBy: user.id }] };
}

// 型を再エクスポート（既存の import { type ... } from "./actions" を壊さないため）
export type {
  AllocationGroupItemSummary,
  TransactionListItem,
  TransactionFilters,
  TransactionSort,
} from "./types";

/** サーバーサイドページネーション導入時に使用予定 */
export async function listTransactions(
  filters?: TransactionFilters,
  sort?: TransactionSort,
  projectId?: number
): Promise<TransactionListItem[]> {
  const session = await getSession();
  const txConfidentialFilter = buildConfidentialFilter(session);

  const where: Record<string, unknown> = {
    deletedAt: null,
    ...(projectId ? { projectId } : {}),
    ...txConfidentialFilter,
  };

  if (filters?.type) {
    where.type = filters.type;
  }
  if (filters?.status) {
    where.status = filters.status;
  }
  if (filters?.counterpartyId) {
    where.counterpartyId = filters.counterpartyId;
  }
  if (filters?.periodFrom) {
    where.periodFrom = { gte: new Date(filters.periodFrom) };
  }
  if (filters?.periodTo) {
    where.periodTo = { lte: new Date(filters.periodTo) };
  }

  const orderBy: Record<string, string>[] = [];
  if (sort?.field) {
    orderBy.push({ [sort.field]: sort.direction });
  } else {
    orderBy.push({ periodFrom: "desc" }, { id: "desc" });
  }

  const records = await prisma.transaction.findMany({
    where,
    include: {
      counterparty: true,
      expenseCategory: true,
      costCenter: true,
      allocationTemplate: {
        include: {
          lines: {
            include: { costCenter: { select: { id: true, name: true } } },
          },
        },
      },
      allocationGroupItems: {
        include: {
          costCenter: { select: { id: true, name: true } },
          invoiceGroup: { select: { invoiceNumber: true } },
          paymentGroup: { select: { targetMonth: true } },
        },
      },
      creator: true,
    },
    orderBy,
  });

  return records.map((r) => mapTransactionRecord(r));
}

/** 削除済み取引一覧を取得 */
export async function listDeletedTransactions(
  projectId?: number
): Promise<TransactionListItem[]> {
  const records = await prisma.transaction.findMany({
    where: {
      deletedAt: { not: null },
      ...(projectId ? { projectId } : {}),
    },
    include: {
      counterparty: true,
      expenseCategory: true,
      costCenter: true,
      allocationTemplate: {
        include: {
          lines: {
            include: { costCenter: { select: { id: true, name: true } } },
          },
        },
      },
      allocationGroupItems: {
        include: {
          costCenter: { select: { id: true, name: true } },
          invoiceGroup: { select: { invoiceNumber: true } },
          paymentGroup: { select: { targetMonth: true } },
        },
      },
      creator: true,
    },
    orderBy: [{ deletedAt: "desc" }, { id: "desc" }],
  });

  return records.map((r) => mapTransactionRecord(r));
}

/** レコードをTransactionListItemに変換するヘルパー */
function mapTransactionRecord(r: {
  id: number;
  type: string;
  counterpartyId: number;
  counterparty: { name: string };
  expenseCategoryId: number | null;
  expenseCategory: { name: string } | null;
  costCenter: { name: string } | null;
  allocationTemplate: {
    id: number;
    name: string;
    lines: {
      costCenterId: number | null;
      costCenter: { id: number; name: string } | null;
    }[];
  } | null;
  allocationGroupItems: {
    costCenterId: number;
    costCenter: { id: number; name: string };
    invoiceGroup: { invoiceNumber: string | null } | null;
    paymentGroup: { targetMonth: Date | null } | null;
  }[];
  amount: number;
  taxAmount: number;
  taxRate: number;
  taxType: string;
  periodFrom: Date;
  periodTo: Date;
  paymentDueDate: Date | null;
  status: string;
  note: string | null;
  isAutoGenerated: boolean;
  sourceType: string | null;
  invoiceGroupId: number | null;
  paymentGroupId: number | null;
  creator: { name: string };
  createdAt: Date;
  updatedAt: Date;
}): TransactionListItem {
  // 按分グループ所属サマリーを構築
  let allocationGroupSummary: AllocationGroupItemSummary[] | null = null;
  if (r.allocationTemplate) {
    const itemMap = new Map(
      r.allocationGroupItems.map((i) => [i.costCenterId, i])
    );
    allocationGroupSummary = r.allocationTemplate.lines
      .filter((l) => l.costCenterId !== null && l.costCenter)
      .map((l) => {
        const item = itemMap.get(l.costCenterId!);
        let groupLabel: string | null = null;
        if (item?.invoiceGroup) {
          groupLabel = item.invoiceGroup.invoiceNumber ?? "請求(下書き)";
        } else if (item?.paymentGroup) {
          const m = item.paymentGroup.targetMonth;
          groupLabel = m ? `支払 ${m.getUTCFullYear()}/${String(m.getUTCMonth() + 1).padStart(2, "0")}` : "支払（対象月未設定）";
        }
        return {
          costCenterId: l.costCenterId!,
          costCenterName: l.costCenter!.name,
          isProcessed: !!item,
          groupLabel,
        };
      });
  }

  return {
    id: r.id,
    type: r.type,
    counterpartyId: r.counterpartyId,
    counterpartyName: r.counterparty.name,
    expenseCategoryId: r.expenseCategoryId,
    expenseCategoryName: r.expenseCategory?.name ?? "（未設定）",
    costCenterName: r.costCenter?.name ?? null,
    allocationTemplateName: r.allocationTemplate?.name ?? null,
    allocationTemplateId: r.allocationTemplate?.id ?? null,
    amount: r.amount,
    taxAmount: r.taxAmount,
    taxRate: r.taxRate,
    taxType: r.taxType,
    periodFrom: toLocalDateString(r.periodFrom),
    periodTo: toLocalDateString(r.periodTo),
    paymentDueDate: r.paymentDueDate
      ? toLocalDateString(r.paymentDueDate)
      : null,
    status: r.status,
    note: r.note,
    isAutoGenerated: r.isAutoGenerated,
    sourceType: r.sourceType,
    invoiceGroupId: r.invoiceGroupId,
    paymentGroupId: r.paymentGroupId,
    createdByName: r.creator.name,
    createdAt: toLocalDateString(r.createdAt),
    updatedAt: toLocalDateString(r.updatedAt),
    allocationGroupSummary,
  };
}

/** 費目マスタ取得 */
export async function getExpenseCategories(): Promise<
  { id: number; name: string; type: string }[]
> {
  const records = await prisma.expenseCategory.findMany({
    where: { deletedAt: null, isActive: true },
    orderBy: { displayOrder: "asc" },
    select: { id: true, name: true, type: true },
  });
  return records;
}

/** インライン取引作成（請求/支払グループ作成時に使用） */
export async function createTransactionInline(data: {
  type: "revenue" | "expense";
  counterpartyId: number;
  expenseCategoryId: number;
  amount: number;
  taxRate: number;
  taxAmount: number;
  taxType: string;
  periodFrom: string;
  periodTo: string;
  note?: string;
  projectId?: number;
}): Promise<{ id: number }> {
  const user = await requireEdit("stp");

  const record = await prisma.transaction.create({
    data: {
      type: data.type,
      counterpartyId: data.counterpartyId,
      expenseCategoryId: data.expenseCategoryId,
      amount: data.amount,
      taxRate: data.taxRate,
      taxAmount: data.taxAmount,
      taxType: data.taxType,
      periodFrom: new Date(data.periodFrom),
      periodTo: new Date(data.periodTo),
      note: data.note ?? null,
      projectId: data.projectId ?? null,
      status: "confirmed",
      sourceType: "manual",
      isAutoGenerated: false,
      createdBy: user.id,
    },
  });

  await recordChangeLog(
    {
      tableName: "Transaction",
      recordId: record.id,
      changeType: "create",
      oldData: null,
      newData: { amount: data.amount, type: data.type, status: "confirmed" },
    },
    user.id
  );

  revalidatePath("/stp/finance/transactions");
  revalidatePath("/stp/finance/invoices");
  revalidatePath("/stp/finance/payment-groups");

  return { id: record.id };
}
