import { prisma } from "@/lib/prisma";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { TransactionsTable } from "./transactions-table";
import type { TransactionListItem } from "./actions";

export default async function TransactionsPage() {
  const [records, counterparties] = await Promise.all([
    prisma.transaction.findMany({
      where: { deletedAt: null },
      include: {
        counterparty: true,
        expenseCategory: true,
        costCenter: true,
        allocationTemplate: true,
        creator: true,
      },
      orderBy: [{ periodFrom: "desc" }, { id: "desc" }],
    }),
    prisma.counterparty.findMany({
      where: { deletedAt: null, isActive: true },
      orderBy: { id: "asc" },
    }),
  ]);

  const formatDate = (date: Date | null): string | null => {
    if (!date) return null;
    return date.toISOString().split("T")[0];
  };

  const data: TransactionListItem[] = records.map((r) => ({
    id: r.id,
    type: r.type,
    counterpartyId: r.counterpartyId,
    counterpartyName: r.counterparty.name,
    expenseCategoryId: r.expenseCategoryId,
    expenseCategoryName: r.expenseCategory.name,
    costCenterName: r.costCenter?.name ?? null,
    allocationTemplateName: r.allocationTemplate?.name ?? null,
    amount: r.amount,
    taxAmount: r.taxAmount,
    taxRate: r.taxRate,
    taxType: r.taxType,
    periodFrom: r.periodFrom.toISOString().split("T")[0],
    periodTo: r.periodTo.toISOString().split("T")[0],
    paymentDueDate: formatDate(r.paymentDueDate),
    status: r.status,
    note: r.note,
    isAutoGenerated: r.isAutoGenerated,
    sourceType: r.sourceType,
    invoiceGroupId: r.invoiceGroupId,
    paymentGroupId: r.paymentGroupId,
    contractId: r.contractId,
    createdByName: r.creator.name,
    createdAt: r.createdAt.toISOString().split("T")[0],
    updatedAt: r.updatedAt.toISOString().split("T")[0],
  }));

  const counterpartyOptions = counterparties.map((c) => ({
    value: String(c.id),
    label: c.name,
  }));

  // サマリー計算
  const totalRevenue = records
    .filter((r) => r.type === "revenue")
    .reduce((sum, r) => sum + r.amount + r.taxAmount, 0);
  const totalExpense = records
    .filter((r) => r.type === "expense")
    .reduce((sum, r) => sum + r.amount + r.taxAmount, 0);
  const unconfirmedCount = records.filter((r) => r.status === "unconfirmed").length;
  const returnedCount = records.filter((r) => r.status === "returned" || r.status === "resubmitted").length;

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-bold">取引一覧</h1>

      <div className={`grid grid-cols-1 gap-4 ${returnedCount > 0 ? "sm:grid-cols-4" : "sm:grid-cols-3"}`}>
        <Card>
          <CardContent className="pt-6">
            <div className="text-sm text-muted-foreground">売上合計（税込）</div>
            <div className="text-2xl font-bold text-emerald-600">
              ¥{totalRevenue.toLocaleString()}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-sm text-muted-foreground">経費合計（税込）</div>
            <div className="text-2xl font-bold text-rose-600">
              ¥{totalExpense.toLocaleString()}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-sm text-muted-foreground">未確認</div>
            <div className="text-2xl font-bold text-orange-600">
              {unconfirmedCount}件
            </div>
          </CardContent>
        </Card>
        {returnedCount > 0 && (
          <Card>
            <CardContent className="pt-6">
              <div className="text-sm text-muted-foreground">差し戻し</div>
              <div className="text-2xl font-bold text-red-600">
                {returnedCount}件
              </div>
            </CardContent>
          </Card>
        )}
      </div>

      <Card>
        <CardHeader>
          <CardTitle>取引一覧</CardTitle>
        </CardHeader>
        <CardContent>
          <TransactionsTable
            data={data}
            counterpartyOptions={counterpartyOptions}
          />
        </CardContent>
      </Card>
    </div>
  );
}
