export type AllocationGroupItemSummary = {
  costCenterId: number;
  costCenterName: string;
  isProcessed: boolean;
  groupLabel: string | null; // 請求書番号 or 支払対象月
};

export type TransactionListItem = {
  id: number;
  type: string;
  counterpartyId: number;
  counterpartyName: string;
  expenseCategoryId: number | null;
  expenseCategoryName: string;
  costCenterName: string | null;
  allocationTemplateName: string | null;
  allocationTemplateId: number | null;
  amount: number;
  taxAmount: number;
  taxRate: number;
  taxType: string;
  periodFrom: string;
  periodTo: string;
  paymentDueDate: string | null;
  status: string;
  note: string | null;
  isAutoGenerated: boolean;
  sourceType: string | null;
  invoiceGroupId: number | null;
  paymentGroupId: number | null;
  createdByName: string;
  createdAt: string;
  updatedAt: string;
  // 按分グループ所属状況
  allocationGroupSummary: AllocationGroupItemSummary[] | null;
};

export type TransactionFilters = {
  type?: "revenue" | "expense";
  status?: string;
  counterpartyId?: number;
  periodFrom?: string;
  periodTo?: string;
};

export type TransactionSort = {
  field: string;
  direction: "asc" | "desc";
};
