"use client";

import { useState, useTransition, useMemo } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { Plus, CheckCircle, Pencil, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { JournalStatusBadge } from "./journal-status-badge";
import { JournalEntryModal } from "./journal-entry-modal";
import { confirmJournalEntry, deleteJournalEntry } from "./actions";
import type { JournalFormData } from "./actions";

type JournalEntryRow = {
  id: number;
  journalDate: Date;
  description: string;
  status: string;
  isAutoGenerated: boolean;
  invoiceGroupId: number | null;
  paymentGroupId: number | null;
  transactionId: number | null;
  approvedAt: Date | null;
  lines: {
    id: number;
    side: string;
    accountId: number;
    amount: number;
    description: string | null;
    account: { id: number; code: string; name: string };
  }[];
  invoiceGroup: {
    id: number;
    invoiceNumber: string | null;
    counterparty: { id: number; name: string };
  } | null;
  paymentGroup: {
    id: number;
    targetMonth: Date;
    counterparty: { id: number; name: string };
  } | null;
  transaction: {
    id: number;
    type: string;
    amount: number;
    counterparty: { id: number; name: string } | null;
  } | null;
  creator: { id: number; name: string } | null;
  approver: { id: number; name: string } | null;
};

type Props = {
  entries: JournalEntryRow[];
  formData: JournalFormData;
};

export function JournalTable({ entries, formData }: Props) {
  const router = useRouter();
  const [isPending, startTransition] = useTransition();
  const [createOpen, setCreateOpen] = useState(false);
  const [editEntry, setEditEntry] = useState<JournalEntryRow | null>(null);
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [searchText, setSearchText] = useState("");

  // フィルタリング
  const filteredEntries = useMemo(() => {
    let result = entries;

    if (statusFilter !== "all") {
      result = result.filter((e) => e.status === statusFilter);
    }

    if (searchText.trim()) {
      const q = searchText.trim().toLowerCase();
      result = result.filter(
        (e) =>
          e.description.toLowerCase().includes(q) ||
          e.lines.some(
            (l) =>
              l.account.name.toLowerCase().includes(q) ||
              l.account.code.toLowerCase().includes(q)
          ) ||
          e.invoiceGroup?.invoiceNumber?.toLowerCase().includes(q) ||
          e.invoiceGroup?.counterparty?.name?.toLowerCase().includes(q) ||
          e.paymentGroup?.counterparty?.name?.toLowerCase().includes(q) ||
          e.transaction?.counterparty?.name?.toLowerCase().includes(q)
      );
    }

    return result;
  }, [entries, statusFilter, searchText]);

  const handleConfirm = (id: number) => {
    startTransition(async () => {
      try {
        await confirmJournalEntry(id);
        toast.success("仕訳を確定しました");
        router.refresh();
      } catch (err) {
        toast.error(
          err instanceof Error ? err.message : "確定に失敗しました"
        );
      }
    });
  };

  const handleDelete = (id: number) => {
    startTransition(async () => {
      try {
        await deleteJournalEntry(id);
        toast.success("仕訳を削除しました");
        router.refresh();
      } catch (err) {
        toast.error(
          err instanceof Error ? err.message : "削除に失敗しました"
        );
      }
    });
  };

  const getSourceLabel = (entry: JournalEntryRow): string => {
    if (entry.invoiceGroup) {
      const num = entry.invoiceGroup.invoiceNumber ?? `#${entry.invoiceGroup.id}`;
      return `請求: ${num} (${entry.invoiceGroup.counterparty.name})`;
    }
    if (entry.paymentGroup) {
      const month = new Date(entry.paymentGroup.targetMonth).toLocaleDateString("ja-JP", {
        year: "numeric",
        month: "short",
      });
      return `支払: ${month} (${entry.paymentGroup.counterparty.name})`;
    }
    if (entry.transaction) {
      const type = entry.transaction.type === "revenue" ? "売上" : "経費";
      const name = entry.transaction.counterparty?.name ?? "";
      return `${type}: ${name}`;
    }
    return "手動仕訳";
  };

  return (
    <div className="space-y-4">
      {/* フィルタ・操作バー */}
      <div className="flex items-center gap-3 flex-wrap">
        <Input
          placeholder="摘要・科目・取引先で検索..."
          value={searchText}
          onChange={(e) => setSearchText(e.target.value)}
          className="w-64"
        />
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-36">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">全てのステータス</SelectItem>
            <SelectItem value="draft">下書き</SelectItem>
            <SelectItem value="confirmed">確定</SelectItem>
          </SelectContent>
        </Select>
        <div className="ml-auto">
          <Button onClick={() => setCreateOpen(true)}>
            <Plus className="h-4 w-4 mr-1" />
            新規仕訳
          </Button>
        </div>
      </div>

      {/* テーブル */}
      {filteredEntries.length === 0 ? (
        <p className="text-muted-foreground text-center py-8">
          仕訳データがありません
        </p>
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b text-left">
                <th className="px-3 py-2 font-medium">仕訳日</th>
                <th className="px-3 py-2 font-medium">摘要</th>
                <th className="px-3 py-2 font-medium">借方</th>
                <th className="px-3 py-2 font-medium">貸方</th>
                <th className="px-3 py-2 font-medium text-right">金額</th>
                <th className="px-3 py-2 font-medium">紐づき先</th>
                <th className="px-3 py-2 font-medium">ステータス</th>
                <th className="px-3 py-2 font-medium">作成者</th>
                <th className="px-3 py-2 font-medium">操作</th>
              </tr>
            </thead>
            <tbody>
              {filteredEntries.map((entry) => {
                const debitLines = entry.lines.filter(
                  (l) => l.side === "debit"
                );
                const creditLines = entry.lines.filter(
                  (l) => l.side === "credit"
                );
                const totalAmount = debitLines.reduce(
                  (sum, l) => sum + l.amount,
                  0
                );

                return (
                  <tr
                    key={entry.id}
                    className="border-b hover:bg-muted/50 group/row"
                  >
                    <td className="px-3 py-2 whitespace-nowrap">
                      {new Date(entry.journalDate).toLocaleDateString("ja-JP")}
                    </td>
                    <td className="px-3 py-2 max-w-[200px] truncate">
                      {entry.isAutoGenerated && (
                        <span className="text-xs bg-blue-100 text-blue-700 rounded px-1 mr-1">
                          自動
                        </span>
                      )}
                      {entry.description}
                    </td>
                    <td className="px-3 py-2">
                      {debitLines.map((l) => (
                        <div key={l.id} className="text-xs">
                          {l.account.name}
                        </div>
                      ))}
                    </td>
                    <td className="px-3 py-2">
                      {creditLines.map((l) => (
                        <div key={l.id} className="text-xs">
                          {l.account.name}
                        </div>
                      ))}
                    </td>
                    <td className="px-3 py-2 text-right whitespace-nowrap">
                      ¥{totalAmount.toLocaleString()}
                    </td>
                    <td className="px-3 py-2 text-xs text-muted-foreground max-w-[150px] truncate">
                      {getSourceLabel(entry)}
                    </td>
                    <td className="px-3 py-2">
                      <JournalStatusBadge status={entry.status} />
                    </td>
                    <td className="px-3 py-2 text-xs text-muted-foreground whitespace-nowrap">
                      {entry.creator?.name ?? "-"}
                      {entry.approver && (
                        <>
                          <br />
                          <span className="text-green-600">
                            確定: {entry.approver.name}
                          </span>
                        </>
                      )}
                    </td>
                    <td className="px-3 py-2">
                      <div className="flex items-center gap-1">
                        {entry.status === "draft" && (
                          <>
                            {/* 編集ボタン */}
                            <Button
                              variant="ghost"
                              size="sm"
                              className="h-8 w-8 p-0"
                              onClick={() => setEditEntry(entry)}
                              disabled={isPending}
                            >
                              <Pencil className="h-4 w-4" />
                            </Button>

                            {/* 確定ボタン */}
                            <AlertDialog>
                              <AlertDialogTrigger asChild>
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  className="h-8 w-8 p-0 text-green-600 hover:text-green-700"
                                  disabled={isPending}
                                >
                                  <CheckCircle className="h-4 w-4" />
                                </Button>
                              </AlertDialogTrigger>
                              <AlertDialogContent>
                                <AlertDialogHeader>
                                  <AlertDialogTitle>
                                    仕訳を確定しますか？
                                  </AlertDialogTitle>
                                  <AlertDialogDescription>
                                    確定後は編集できなくなります。仕訳内容をご確認ください。
                                    <br />
                                    <br />
                                    <strong>摘要:</strong>{" "}
                                    {entry.description}
                                    <br />
                                    <strong>金額:</strong> ¥
                                    {totalAmount.toLocaleString()}
                                  </AlertDialogDescription>
                                </AlertDialogHeader>
                                <AlertDialogFooter>
                                  <AlertDialogCancel>
                                    キャンセル
                                  </AlertDialogCancel>
                                  <AlertDialogAction
                                    onClick={() => handleConfirm(entry.id)}
                                    disabled={isPending}
                                  >
                                    確定する
                                  </AlertDialogAction>
                                </AlertDialogFooter>
                              </AlertDialogContent>
                            </AlertDialog>

                            {/* 削除ボタン */}
                            <AlertDialog>
                              <AlertDialogTrigger asChild>
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  className="h-8 w-8 p-0 text-muted-foreground hover:text-red-600"
                                  disabled={isPending}
                                >
                                  <Trash2 className="h-4 w-4" />
                                </Button>
                              </AlertDialogTrigger>
                              <AlertDialogContent>
                                <AlertDialogHeader>
                                  <AlertDialogTitle>
                                    仕訳を削除しますか？
                                  </AlertDialogTitle>
                                  <AlertDialogDescription>
                                    この操作は取り消せません。下書きの仕訳が削除されます。
                                  </AlertDialogDescription>
                                </AlertDialogHeader>
                                <AlertDialogFooter>
                                  <AlertDialogCancel>
                                    キャンセル
                                  </AlertDialogCancel>
                                  <AlertDialogAction
                                    onClick={() => handleDelete(entry.id)}
                                    disabled={isPending}
                                    className="bg-red-600 hover:bg-red-700"
                                  >
                                    削除する
                                  </AlertDialogAction>
                                </AlertDialogFooter>
                              </AlertDialogContent>
                            </AlertDialog>
                          </>
                        )}
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* 新規作成モーダル */}
      <JournalEntryModal
        open={createOpen}
        onOpenChange={setCreateOpen}
        formData={formData}
        onSuccess={() => router.refresh()}
      />

      {/* 編集モーダル */}
      {editEntry && (
        <JournalEntryModal
          open={!!editEntry}
          onOpenChange={(o) => {
            if (!o) setEditEntry(null);
          }}
          formData={formData}
          editEntry={editEntry}
          onSuccess={() => {
            setEditEntry(null);
            router.refresh();
          }}
        />
      )}
    </div>
  );
}
