import { prisma } from "@/lib/prisma";
import { NextResponse } from "next/server";

// JSON文字列を配列にパースするヘルパー
const parseJsonArray = (json: string | null): string[] => {
  if (!json) return [];
  try {
    const parsed = JSON.parse(json);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
};

// 日時をフォーマットするヘルパー（サーバー側で固定フォーマット）
const formatDateTime = (date: Date): string => {
  return date.toLocaleDateString("ja-JP", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    timeZone: "Asia/Tokyo",
  });
};

export async function GET() {
  const [submissions, masterCompanies, stpCompanies, agents] = await Promise.all([
    prisma.stpLeadFormSubmission.findMany({
      include: {
        token: {
          include: {
            agent: {
              include: {
                company: true,
              },
            },
          },
        },
        proposals: true,
      },
      orderBy: { submittedAt: "desc" },
    }),
    prisma.masterStellaCompany.findMany({
      orderBy: { companyCode: "desc" },
    }),
    // STPに登録済みの企業とその代理店情報を取得
    prisma.stpCompany.findMany({
      select: {
        companyId: true,
        agentId: true,
        agent: {
          include: {
            company: true,
          },
        },
      },
    }),
    // 代理店一覧
    prisma.stpAgent.findMany({
      where: { status: "アクティブ" },
      include: { company: true },
      orderBy: { id: "asc" },
    }),
  ]);

  // STP企業のマップ（companyId -> agentId, agentName）
  const stpCompanyMap = new Map(
    stpCompanies.map((c) => [
      c.companyId,
      {
        agentId: c.agentId,
        agentName: c.agent?.company.name || null,
      },
    ])
  );

  // 紐付け可能な企業（全企業、STP登録済みは印と代理店情報を付ける）
  const companyOptions = masterCompanies.map((c) => {
    const stpInfo = stpCompanyMap.get(c.id);
    return {
      value: String(c.id),
      label: stpInfo
        ? `${c.companyCode} ${c.name} [STP登録済]`
        : `${c.companyCode} ${c.name}`,
      companyName: c.name,
      isInStp: !!stpInfo,
      stpAgentId: stpInfo?.agentId ?? null,
      stpAgentName: stpInfo?.agentName ?? null,
      industry: c.industry || "",
      revenueScale: c.revenueScale || "",
      websiteUrl: c.websiteUrl || "",
    };
  });

  // 代理店選択肢
  const agentOptions = agents.map((a) => ({
    value: String(a.id),
    label: a.company.name,
  }));

  const data = submissions.map((s) => ({
    id: s.id,
    companyName: s.companyName,
    contactName: s.contactName,
    contactEmail: s.contactEmail,
    contactPhone: s.contactPhone,
    agentId: s.token.agentId,
    agentName: s.token.agent.company.name,
    status: s.status,
    submittedAt: formatDateTime(s.submittedAt),
    submittedAtRaw: s.submittedAt.toISOString(),
    processedAt: s.processedAt ? formatDateTime(s.processedAt) : null,
    processingNote: s.processingNote,
    masterCompanyId: s.masterCompanyId,
    pastHiringJobTypes: parseJsonArray(s.pastHiringJobTypes),
    pastRecruitingCostAgency: s.pastRecruitingCostAgency,
    pastRecruitingCostAds: s.pastRecruitingCostAds,
    pastRecruitingCostReferral: s.pastRecruitingCostReferral,
    pastRecruitingCostOther: s.pastRecruitingCostOther,
    pastHiringCount: s.pastHiringCount,
    desiredJobTypes: parseJsonArray(s.desiredJobTypes),
    annualBudget: s.annualBudget,
    annualHiringTarget: s.annualHiringTarget,
    hiringAreas: parseJsonArray(s.hiringAreas),
    hiringTimeline: s.hiringTimeline,
    ageRangeMin: s.ageRangeMin,
    ageRangeMax: s.ageRangeMax,
    requiredConditions: s.requiredConditions,
    preferredConditions: s.preferredConditions,
    proposals: s.proposals.map((p) => ({
      id: p.id,
      proposalNumber: p.proposalNumber,
      title: p.title,
      status: p.status,
      filePath: p.filePath,
      fileName: p.fileName,
      externalUrl: p.externalUrl,
      externalService: p.externalService,
      isAutoGenerated: p.isAutoGenerated,
    })),
  }));

  return NextResponse.json({ submissions: data, companyOptions, agentOptions });
}
