"use client";

import { useState, useEffect, useCallback } from "react";
import { useRouter } from "next/navigation";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  addProposal,
  updateProposal,
  deleteProposal,
  getProposals,
} from "@/app/stp/proposal-actions";
import { Plus, Pencil, Trash2, X, FileText, ExternalLink } from "lucide-react";
import { toast } from "sonner";
import { TextPreviewCell } from "@/components/text-preview-cell";
import { FileUpload } from "@/components/file-upload";
import DatePicker, { registerLocale } from "react-datepicker";
import { ja } from "date-fns/locale";
import "react-datepicker/dist/react-datepicker.css";

// 日本語ロケールを登録
registerLocale("ja", ja);

type Proposal = {
  id: number;
  stpCompanyId: number | null;
  submissionId: number | null;
  title: string;
  proposalNumber: string | null;
  filePath: string | null;
  fileName: string | null;
  externalUrl: string | null;
  externalService: string | null;
  status: string;
  sentAt: string | null;
  assignedTo: string | null;
  note: string | null;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
};

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  stpCompanyId: number;
  companyName: string;
  staffOptions: { value: string; label: string }[];
};

const statusOptions = [
  { value: "draft", label: "下書き" },
  { value: "sent", label: "送付済み" },
  { value: "viewed", label: "閲覧済み" },
  { value: "accepted", label: "受諾" },
  { value: "rejected", label: "辞退" },
];

const externalServiceOptions = [
  { value: "canva", label: "Canva" },
  { value: "google_docs", label: "Google Docs" },
  { value: "other", label: "その他" },
];

type FormData = {
  title: string;
  filePath: string;
  fileName: string;
  externalUrl: string;
  externalService: string;
  status: string;
  sentAt: Date | null;
  assignedTo: string;
  note: string;
};

const EMPTY_FORM_DATA: FormData = {
  title: "",
  filePath: "",
  fileName: "",
  externalUrl: "",
  externalService: "",
  status: "draft",
  sentAt: null,
  assignedTo: "",
  note: "",
};

export function ProposalModal({
  open,
  onOpenChange,
  stpCompanyId,
  companyName,
  staffOptions,
}: Props) {
  const router = useRouter();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formOpen, setFormOpen] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [formData, setFormData] = useState<FormData>(EMPTY_FORM_DATA);
  const [localProposals, setLocalProposals] = useState<Proposal[]>([]);
  const [initialLoading, setInitialLoading] = useState(true);

  // モーダルが開くたびにサーバーから最新データを取得
  const loadProposals = useCallback(async () => {
    setInitialLoading(true);
    try {
      const data = await getProposals(stpCompanyId);
      setLocalProposals(data);
    } catch (error) {
      console.error("Error fetching proposals:", error);
    } finally {
      setInitialLoading(false);
    }
  }, [stpCompanyId]);

  useEffect(() => {
    if (open) {
      loadProposals();
    }
  }, [open, loadProposals]);

  const resetForm = () => {
    setFormData(EMPTY_FORM_DATA);
    setEditingId(null);
    setFormOpen(false);
  };

  const handleAdd = () => {
    resetForm();
    setFormOpen(true);
  };

  const parseDate = (dateStr: string | null | undefined): Date | null => {
    if (!dateStr) return null;
    return new Date(dateStr);
  };

  const handleEdit = (proposal: Proposal) => {
    setFormData({
      title: proposal.title || "",
      filePath: proposal.filePath || "",
      fileName: proposal.fileName || "",
      externalUrl: proposal.externalUrl || "",
      externalService: proposal.externalService || "",
      status: proposal.status || "draft",
      sentAt: parseDate(proposal.sentAt),
      assignedTo: proposal.assignedTo || "",
      note: proposal.note || "",
    });
    setEditingId(proposal.id);
    setFormOpen(true);
  };

  const handleDelete = async (id: number) => {
    if (!confirm("この提案書を削除してもよろしいですか？")) return;

    try {
      const result = await deleteProposal(id);
      if (result.success) {
        setLocalProposals((prev) => prev.filter((p) => p.id !== id));
        toast.success("提案書を削除しました");
        router.refresh();
      } else {
        toast.error(result.error || "削除に失敗しました");
      }
    } catch (error) {
      console.error("Error deleting proposal:", error);
      toast.error("削除に失敗しました");
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!formData.title) {
      toast.error("タイトルは必須です");
      return;
    }

    setIsSubmitting(true);
    try {
      const data = {
        title: formData.title,
        filePath: formData.filePath || null,
        fileName: formData.fileName || null,
        externalUrl: formData.externalUrl || null,
        externalService: formData.externalService || null,
        status: formData.status,
        sentAt: formData.sentAt?.toISOString().split("T")[0] || null,
        assignedTo: formData.assignedTo || null,
        note: formData.note || null,
      };

      if (editingId) {
        const result = await updateProposal(editingId, data);
        if (result.success) {
          toast.success("提案書を更新しました");
        } else {
          toast.error(result.error || "更新に失敗しました");
          return;
        }
      } else {
        const result = await addProposal(stpCompanyId, data);
        if (result.success) {
          toast.success("提案書を追加しました");
        } else {
          toast.error(result.error || "追加に失敗しました");
          return;
        }
      }

      resetForm();
      await loadProposals();
      router.refresh();
    } catch (error) {
      console.error("Error saving proposal:", error);
      toast.error("保存に失敗しました");
    } finally {
      setIsSubmitting(false);
    }
  };

  const formatDate = (dateStr: string | null | undefined) => {
    if (!dateStr) return "-";
    return new Date(dateStr).toLocaleDateString("ja-JP");
  };

  const getStatusLabel = (status: string | null | undefined) => {
    if (!status) return "-";
    return statusOptions.find((o) => o.value === status)?.label || status;
  };

  const getExternalServiceLabel = (service: string | null | undefined) => {
    if (!service) return "";
    return externalServiceOptions.find((o) => o.value === service)?.label || service;
  };

  const datePickerClassName = "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50";

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>提案書管理 - {companyName}</DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          {/* 追加ボタン */}
          <div className="flex justify-end">
            <Button onClick={handleAdd} size="sm" disabled={formOpen}>
              <Plus className="h-4 w-4 mr-1" />
              提案書を追加
            </Button>
          </div>

          {/* フォーム（折りたたみ） */}
          {formOpen && (
            <div className="border rounded-lg p-4 bg-gray-50">
              <div className="flex justify-between items-center mb-4">
                <h3 className="font-medium">
                  {editingId ? "提案書を編集" : "新規提案書を追加"}
                </h3>
                <Button variant="ghost" size="sm" onClick={resetForm}>
                  <X className="h-4 w-4" />
                </Button>
              </div>

              <form onSubmit={handleSubmit} className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  {/* タイトル */}
                  <div className="col-span-2">
                    <Label htmlFor="title">
                      タイトル <span className="text-red-500">*</span>
                    </Label>
                    <Input
                      id="title"
                      value={formData.title}
                      onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                      placeholder="提案書タイトル"
                    />
                  </div>

                  {/* ステータス */}
                  <div>
                    <Label htmlFor="status">ステータス</Label>
                    <Select
                      value={formData.status}
                      onValueChange={(value) => setFormData({ ...formData, status: value })}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="選択してください" />
                      </SelectTrigger>
                      <SelectContent>
                        {statusOptions.map((option) => (
                          <SelectItem key={option.value} value={option.value}>
                            {option.label}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  {/* 送付日 */}
                  <div>
                    <Label htmlFor="sentAt">送付日</Label>
                    <DatePicker
                      selected={formData.sentAt}
                      onChange={(date: Date | null) => setFormData({ ...formData, sentAt: date })}
                      dateFormat="yyyy/MM/dd"
                      locale="ja"
                      placeholderText="日付を選択"
                      isClearable
                      className={datePickerClassName}
                      wrapperClassName="w-full"
                      calendarClassName="shadow-lg"
                    />
                  </div>

                  {/* 担当者 */}
                  <div>
                    <Label htmlFor="assignedTo">担当者</Label>
                    <Select
                      value={formData.assignedTo}
                      onValueChange={(value) => setFormData({ ...formData, assignedTo: value })}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="選択してください" />
                      </SelectTrigger>
                      <SelectContent>
                        {staffOptions.map((option) => (
                          <SelectItem key={option.value} value={option.value}>
                            {option.label}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  {/* 空のセル（レイアウト調整） */}
                  <div></div>

                  {/* ファイルアップロード */}
                  <div className="col-span-2">
                    <Label htmlFor="fileUpload">提案書ファイル</Label>
                    <FileUpload
                      value={{
                        filePath: formData.filePath || null,
                        fileName: formData.fileName || null,
                      }}
                      onChange={(newValue) => {
                        setFormData({
                          ...formData,
                          filePath: newValue.filePath || "",
                          fileName: newValue.fileName || "",
                        });
                      }}
                    />
                  </div>

                  {/* 外部URL */}
                  <div>
                    <Label htmlFor="externalUrl">外部URL</Label>
                    <Input
                      id="externalUrl"
                      value={formData.externalUrl}
                      onChange={(e) => setFormData({ ...formData, externalUrl: e.target.value })}
                      placeholder="https://..."
                    />
                  </div>

                  {/* 外部サービス */}
                  <div>
                    <Label htmlFor="externalService">外部サービス</Label>
                    <Select
                      value={formData.externalService}
                      onValueChange={(value) => setFormData({ ...formData, externalService: value })}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="選択してください" />
                      </SelectTrigger>
                      <SelectContent>
                        {externalServiceOptions.map((option) => (
                          <SelectItem key={option.value} value={option.value}>
                            {option.label}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                {/* 備考 */}
                <div>
                  <Label htmlFor="note">備考</Label>
                  <Textarea
                    id="note"
                    value={formData.note}
                    onChange={(e) => setFormData({ ...formData, note: e.target.value })}
                    placeholder="備考"
                    rows={2}
                  />
                </div>

                <div className="flex justify-end gap-2">
                  <Button type="button" variant="outline" onClick={resetForm}>
                    キャンセル
                  </Button>
                  <Button type="submit" disabled={isSubmitting}>
                    {isSubmitting ? "保存中..." : "保存"}
                  </Button>
                </div>
              </form>
            </div>
          )}

          {/* 提案書一覧テーブル */}
          {initialLoading ? (
            <div className="text-center py-8 text-gray-500">
              読み込み中...
            </div>
          ) : localProposals.length > 0 ? (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>提案番号</TableHead>
                  <TableHead>タイトル</TableHead>
                  <TableHead>ステータス</TableHead>
                  <TableHead>送付日</TableHead>
                  <TableHead>担当者</TableHead>
                  <TableHead>ファイル/URL</TableHead>
                  <TableHead>備考</TableHead>
                  <TableHead className="w-[100px]">操作</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {localProposals.map((proposal) => (
                  <TableRow key={proposal.id}>
                    <TableCell className="font-mono text-sm">
                      {proposal.proposalNumber || "-"}
                      {proposal.isAutoGenerated && (
                        <span className="ml-1 text-xs text-gray-400">(自動)</span>
                      )}
                    </TableCell>
                    <TableCell className="font-medium">{proposal.title}</TableCell>
                    <TableCell>{getStatusLabel(proposal.status)}</TableCell>
                    <TableCell>{formatDate(proposal.sentAt)}</TableCell>
                    <TableCell>{proposal.assignedTo || "-"}</TableCell>
                    <TableCell>
                      <div className="flex items-center gap-1">
                        {proposal.filePath && proposal.fileName && (
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => window.open(proposal.filePath!, "_blank")}
                            className="flex items-center gap-1 text-blue-600"
                            title={proposal.fileName}
                          >
                            <FileText className="h-4 w-4" />
                            <ExternalLink className="h-3 w-3" />
                          </Button>
                        )}
                        {proposal.externalUrl && (
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => window.open(proposal.externalUrl!, "_blank")}
                            className="flex items-center gap-1 text-green-600"
                            title={getExternalServiceLabel(proposal.externalService) || proposal.externalUrl}
                          >
                            <ExternalLink className="h-4 w-4" />
                            <span className="text-xs">{getExternalServiceLabel(proposal.externalService)}</span>
                          </Button>
                        )}
                        {!proposal.filePath && !proposal.externalUrl && "-"}
                      </div>
                    </TableCell>
                    <TableCell>
                      <TextPreviewCell text={proposal.note} title="備考" />
                    </TableCell>
                    <TableCell>
                      <div className="flex gap-1">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleEdit(proposal)}
                        >
                          <Pencil className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleDelete(proposal.id)}
                        >
                          <Trash2 className="h-4 w-4 text-red-500" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          ) : (
            <div className="text-center py-8 text-gray-500">
              提案書が登録されていません
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
