"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { useRouter } from "next/navigation";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import {
  addProposal,
  updateProposal,
  deleteProposal,
  getProposals,
  lockAllUnlockedSlides,
} from "@/app/stp/proposal-actions";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Plus, Pencil, Trash2, X, FileText, ExternalLink, FileEdit, ChevronDown, ChevronUp, AlertTriangle, Lock } from "lucide-react";
import Link from "next/link";
import { toast } from "sonner";
import { FileUpload } from "@/components/file-upload";
import { toLocalDateString } from "@/lib/utils";
import DatePicker, { registerLocale } from "react-datepicker";
import { ja } from "date-fns/locale";
import "react-datepicker/dist/react-datepicker.css";
import { useTimedFormCache } from "@/hooks/use-timed-form-cache";

// 日本語ロケールを登録
registerLocale("ja", ja);

type Proposal = {
  id: number;
  stpCompanyId: number | null;
  submissionId: number | null;
  title: string;
  proposalNumber: string | null;
  filePath: string | null;
  fileName: string | null;
  externalUrl: string | null;
  externalService: string | null;
  status: string;
  sentAt: string | null;
  assignedTo: string | null;
  note: string | null;
  isAutoGenerated: boolean;
  hasProposalContent: boolean;
  sourceProposalId: number | null;
  slideVersion: number | null;
  hasUnlockedSlides: boolean;
  createdAt: string;
  updatedAt: string;
};

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  stpCompanyId: number;
  companyName: string;
  staffOptions: { value: string; label: string }[];
};

const statusOptions = [
  { value: "draft", label: "下書き" },
  { value: "completed", label: "完成" },
  { value: "sent", label: "送付済み" },
  { value: "viewed", label: "閲覧済み" },
  { value: "accepted", label: "受諾" },
  { value: "rejected", label: "辞退" },
];

const statusColors: Record<string, string> = {
  draft: "bg-gray-100 text-gray-700",
  completed: "bg-blue-100 text-blue-700",
  sent: "bg-yellow-100 text-yellow-700",
  viewed: "bg-purple-100 text-purple-700",
  accepted: "bg-green-100 text-green-700",
  rejected: "bg-red-100 text-red-700",
};

const externalServiceOptions = [
  { value: "canva", label: "Canva" },
  { value: "google_docs", label: "Google ドキュメント" },
  { value: "google_sheets", label: "Google スプレッドシート" },
  { value: "google_slides", label: "Google スライド" },
  { value: "google_forms", label: "Google フォーム" },
  { value: "other", label: "その他" },
];

type FormData = {
  title: string;
  filePath: string;
  fileName: string;
  externalUrl: string;
  externalService: string;
  status: string;
  sentAt: Date | null;
  assignedTo: string;
  note: string;
};

const EMPTY_FORM_DATA: FormData = {
  title: "",
  filePath: "",
  fileName: "",
  externalUrl: "",
  externalService: "",
  status: "draft",
  sentAt: null,
  assignedTo: "",
  note: "",
};

export function ProposalModal({
  open,
  onOpenChange,
  stpCompanyId,
  companyName,
  staffOptions,
}: Props) {
  const router = useRouter();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formOpen, setFormOpen] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [formData, setFormData] = useState<FormData>(EMPTY_FORM_DATA);
  const [localProposals, setLocalProposals] = useState<Proposal[]>([]);
  const [editorProposals, setEditorProposals] = useState<{ id: number; title: string; proposalNumber: string | null; createdAt: string; unlockedSlideVersions: number[] }[]>([]);
  const [initialLoading, setInitialLoading] = useState(true);
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [activeTab, setActiveTab] = useState("proposals");
  const [isLockingAll, setIsLockingAll] = useState(false);

  type CachedState = {
    formData: FormData;
    editingId: number | null;
    formOpen: boolean;
  };
  const { restore, save, clear } = useTimedFormCache<CachedState>(
    `proposal-${stpCompanyId}`
  );
  const formStateRef = useRef<CachedState>({
    formData: EMPTY_FORM_DATA,
    editingId: null,
    formOpen: false,
  });
  formStateRef.current = { formData, editingId, formOpen };

  // クローズ時にキャッシュ保存
  useEffect(() => {
    if (!open) return;
    return () => {
      save(formStateRef.current);
    };
  }, [open, save]);

  // モーダルが開くたびにサーバーから最新データを取得
  const loadProposals = useCallback(async () => {
    setInitialLoading(true);
    try {
      const data = await getProposals(stpCompanyId);
      setLocalProposals(data.proposals);
      setEditorProposals(data.editorProposals);
    } catch (error) {
      console.error("Error fetching proposals:", error);
    } finally {
      setInitialLoading(false);
    }
  }, [stpCompanyId]);

  useEffect(() => {
    if (open) {
      loadProposals();
      const cached = restore();
      if (cached) {
        setFormData(cached.formData);
        setEditingId(cached.editingId);
        setFormOpen(cached.formOpen);
      } else {
        setFormData(EMPTY_FORM_DATA);
        setEditingId(null);
        setFormOpen(false);
      }
    }
  }, [open, loadProposals, restore]);

  const resetForm = () => {
    setFormData(EMPTY_FORM_DATA);
    setEditingId(null);
    setFormOpen(false);
    setShowAdvanced(false);
  };

  const handleAdd = () => {
    resetForm();
    setFormOpen(true);
  };

  const parseDate = (dateStr: string | null | undefined): Date | null => {
    if (!dateStr) return null;
    return new Date(dateStr);
  };

  const handleEdit = (proposal: Proposal) => {
    setFormData({
      title: proposal.title || "",
      filePath: proposal.filePath || "",
      fileName: proposal.fileName || "",
      externalUrl: proposal.externalUrl || "",
      externalService: proposal.externalService || "",
      status: proposal.status || "draft",
      sentAt: parseDate(proposal.sentAt),
      assignedTo: proposal.assignedTo || "",
      note: proposal.note || "",
    });
    setEditingId(proposal.id);
    setFormOpen(true);
    // 外部URLや備考がある場合は詳細を開く
    if (proposal.externalUrl || proposal.note) {
      setShowAdvanced(true);
    }
  };

  const handleDelete = async (id: number) => {
    if (!confirm("この提案書を削除してもよろしいですか？")) return;

    try {
      const result = await deleteProposal(id);
      if (result.success) {
        setLocalProposals((prev) => prev.filter((p) => p.id !== id));
        toast.success("提案書を削除しました");
        router.refresh();
      } else {
        toast.error(result.error || "削除に失敗しました");
      }
    } catch (error) {
      console.error("Error deleting proposal:", error);
      toast.error("削除に失敗しました");
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!formData.title) {
      toast.error("タイトルは必須です");
      return;
    }

    setIsSubmitting(true);
    try {
      const data = {
        title: formData.title,
        filePath: formData.filePath || null,
        fileName: formData.fileName || null,
        externalUrl: formData.externalUrl || null,
        externalService: formData.externalService || null,
        status: formData.status,
        sentAt: formData.sentAt ? toLocalDateString(formData.sentAt) : null,
        assignedTo: formData.assignedTo || null,
        note: formData.note || null,
      };

      if (editingId) {
        const result = await updateProposal(editingId, data);
        if (result.success) {
          toast.success("提案書を更新しました");
        } else {
          toast.error(result.error || "更新に失敗しました");
          return;
        }
      } else {
        const result = await addProposal(stpCompanyId, data);
        if (result.success) {
          toast.success("提案書を追加しました");
        } else {
          toast.error(result.error || "追加に失敗しました");
          return;
        }
      }

      resetForm();
      await loadProposals();
      router.refresh();
    } catch (error) {
      console.error("Error saving proposal:", error);
      toast.error("保存に失敗しました");
    } finally {
      setIsSubmitting(false);
    }
  };

  const totalUnlockedCount = editorProposals.reduce(
    (sum, ep) => sum + ep.unlockedSlideVersions.length,
    0,
  );

  const handleLockAllSlides = async () => {
    setIsLockingAll(true);
    try {
      for (const ep of editorProposals) {
        if (ep.unlockedSlideVersions.length > 0) {
          await lockAllUnlockedSlides(ep.id);
        }
      }
      toast.success("すべてのスライド権限を閲覧専用に戻しました");
      await loadProposals();
    } catch {
      toast.error("権限の戻しに失敗しました");
    } finally {
      setIsLockingAll(false);
    }
  };

  const formatDate = (dateStr: string | null | undefined) => {
    if (!dateStr) return null;
    return new Date(dateStr).toLocaleDateString("ja-JP");
  };

  const getStatusLabel = (status: string | null | undefined) => {
    if (!status) return "-";
    return statusOptions.find((o) => o.value === status)?.label || status;
  };

  const getExternalServiceLabel = (service: string | null | undefined) => {
    if (!service) return "";
    return externalServiceOptions.find((o) => o.value === service)?.label || service;
  };

  const datePickerClassName = "flex h-9 w-full rounded-md border border-input bg-background px-3 py-1 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50";

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent size="mixed" className="flex flex-col p-0">
        <DialogHeader className="px-6 pt-6 pb-4 border-b shrink-0">
          <div className="flex items-center justify-between">
            <DialogTitle className="text-lg">提案書管理 - {companyName}</DialogTitle>
            {(editorProposals.length === 0 || activeTab === "proposals") && (
              <Button onClick={handleAdd} size="sm" disabled={formOpen} variant="outline">
                <Plus className="h-4 w-4 mr-1" />
                追加
              </Button>
            )}
          </div>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto px-6 py-4 space-y-4">
          {editorProposals.length > 0 ? (
            <Tabs value={activeTab} onValueChange={setActiveTab}>
              <TabsList className="w-full">
                <TabsTrigger value="proposals" className="flex-1">提案書一覧</TabsTrigger>
                <TabsTrigger value="editor" className="flex-1">リード回答の提案書</TabsTrigger>
              </TabsList>

              <TabsContent value="proposals" className="space-y-4 mt-4">
                {/* 権限未戻し警告バナー */}
                {totalUnlockedCount > 0 && (
                  <div className="flex items-center gap-2 rounded-lg border border-yellow-300 bg-yellow-50 px-4 py-2.5">
                    <AlertTriangle className="h-4 w-4 text-yellow-600 shrink-0" />
                    <span className="text-sm text-yellow-800 flex-1">
                      編集権限が戻されていないスライドがあります（{totalUnlockedCount}件）
                    </span>
                    <Button
                      variant="outline"
                      size="sm"
                      className="h-7 text-xs border-yellow-400 hover:bg-yellow-100"
                      onClick={handleLockAllSlides}
                      disabled={isLockingAll}
                    >
                      <Lock className="h-3 w-3 mr-1" />
                      {isLockingAll ? "処理中..." : "すべての権限を戻す"}
                    </Button>
                  </div>
                )}

                {/* フォーム（折りたたみ） */}
                {formOpen && (
                  <div className="border rounded-lg p-4 bg-gray-50/80">
                    <div className="flex justify-between items-center mb-3">
                      <h3 className="font-medium text-sm">
                        {editingId ? "提案書を編集" : "新規提案書"}
                      </h3>
                      <Button variant="ghost" size="sm" onClick={resetForm} className="h-7 w-7 p-0">
                        <X className="h-4 w-4" />
                      </Button>
                    </div>

                    <form onSubmit={handleSubmit} className="space-y-3">
                      {/* 1行目: タイトル + ステータス */}
                      <div className="grid grid-cols-3 gap-3">
                        <div className="col-span-2 space-y-1">
                          <Label className="text-xs">
                            タイトル <span className="text-red-500">*</span>
                          </Label>
                          <Input
                            value={formData.title}
                            onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                            placeholder="提案書タイトル"
                            className="h-9"
                          />
                        </div>
                        <div className="space-y-1">
                          <Label className="text-xs">ステータス</Label>
                          <Select
                            value={formData.status}
                            onValueChange={(value) => setFormData({ ...formData, status: value })}
                          >
                            <SelectTrigger className="h-9">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              {statusOptions.map((option) => (
                                <SelectItem key={option.value} value={option.value}>
                                  {option.label}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>
                      </div>

                      {/* 2行目: 担当者 + 送付日 */}
                      <div className="grid grid-cols-3 gap-3">
                        <div className="space-y-1">
                          <Label className="text-xs">担当者</Label>
                          <Select
                            value={formData.assignedTo}
                            onValueChange={(value) => setFormData({ ...formData, assignedTo: value })}
                          >
                            <SelectTrigger className="h-9">
                              <SelectValue placeholder="選択" />
                            </SelectTrigger>
                            <SelectContent>
                              {staffOptions.map((option) => (
                                <SelectItem key={option.value} value={option.value}>
                                  {option.label}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>
                        <div className="space-y-1">
                          <Label className="text-xs">送付日</Label>
                          <DatePicker
                            selected={formData.sentAt}
                            onChange={(date: Date | null) => setFormData({ ...formData, sentAt: date })}
                            dateFormat="yyyy/MM/dd"
                            locale="ja"
                            placeholderText="日付を選択"
                            isClearable
                            className={datePickerClassName}
                            wrapperClassName="w-full"
                            calendarClassName="shadow-lg"
                          />
                        </div>
                      </div>

                      {/* ファイルアップロード */}
                      <div className="space-y-1">
                        <Label className="text-xs">提案書ファイル</Label>
                        <FileUpload
                          value={{
                            filePath: formData.filePath || null,
                            fileName: formData.fileName || null,
                          }}
                          onChange={(newValue) => {
                            setFormData({
                              ...formData,
                              filePath: newValue.filePath || "",
                              fileName: newValue.fileName || "",
                            });
                          }}
                        />
                      </div>

                      {/* 詳細設定（トグル） */}
                      <button
                        type="button"
                        className="flex items-center gap-1 text-xs text-gray-500 hover:text-gray-700"
                        onClick={() => setShowAdvanced(!showAdvanced)}
                      >
                        {showAdvanced ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}
                        外部URL・備考
                      </button>

                      {showAdvanced && (
                        <div className="space-y-3 pt-1">
                          <div className="grid grid-cols-2 gap-3">
                            <div className="space-y-1">
                              <Label className="text-xs">外部URL</Label>
                              <Input
                                value={formData.externalUrl}
                                onChange={(e) => setFormData({ ...formData, externalUrl: e.target.value })}
                                placeholder="https://..."
                                className="h-9"
                              />
                            </div>
                            <div className="space-y-1">
                              <Label className="text-xs">外部サービス</Label>
                              <Select
                                value={formData.externalService || "__none__"}
                                onValueChange={(value) => setFormData({ ...formData, externalService: value === "__none__" ? "" : value })}
                              >
                                <SelectTrigger className="h-9">
                                  <SelectValue placeholder="選択" />
                                </SelectTrigger>
                                <SelectContent>
                                  <SelectItem value="__none__" className="text-gray-400">選択なし</SelectItem>
                                  {externalServiceOptions.map((option) => (
                                    <SelectItem key={option.value} value={option.value}>
                                      {option.label}
                                    </SelectItem>
                                  ))}
                                </SelectContent>
                              </Select>
                            </div>
                          </div>
                          <div className="space-y-1">
                            <Label className="text-xs">備考</Label>
                            <Textarea
                              value={formData.note}
                              onChange={(e) => setFormData({ ...formData, note: e.target.value })}
                              placeholder="備考"
                              rows={2}
                              className="text-sm"
                            />
                          </div>
                        </div>
                      )}

                      <div className="flex justify-end gap-2 pt-1">
                        <Button type="button" variant="outline" size="sm" onClick={resetForm}>
                          キャンセル
                        </Button>
                        <Button type="submit" size="sm" disabled={isSubmitting}>
                          {isSubmitting ? "保存中..." : "保存"}
                        </Button>
                      </div>
                    </form>
                  </div>
                )}

                {/* 提案書一覧（カードレイアウト） */}
                {initialLoading ? (
                  <div className="text-center py-8 text-gray-500 text-sm">
                    読み込み中...
                  </div>
                ) : localProposals.length > 0 ? (
                  <div className="space-y-2">
                    {localProposals.map((proposal) => (
                      <div
                        key={proposal.id}
                        className="border rounded-lg p-3 hover:bg-gray-50/50 transition-colors"
                      >
                        {/* 上段: タイトル行 */}
                        <div className="flex items-start justify-between gap-2">
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2 flex-wrap">
                              <span className="font-medium text-sm truncate">
                                {proposal.title}
                              </span>
                              <Badge
                                variant="secondary"
                                className={`text-[10px] px-1.5 py-0 h-5 ${statusColors[proposal.status] || ""}`}
                              >
                                {getStatusLabel(proposal.status)}
                              </Badge>
                              {proposal.isAutoGenerated && (
                                <span className="text-[10px] bg-blue-50 text-blue-600 px-1.5 py-0.5 rounded">
                                  自動生成
                                </span>
                              )}
                              {proposal.slideVersion && (
                                <span className="text-[10px] bg-purple-50 text-purple-600 px-1.5 py-0.5 rounded">
                                  ver.{proposal.slideVersion}
                                </span>
                              )}
                              {proposal.hasUnlockedSlides && (
                                <span className="text-[10px] bg-yellow-50 text-yellow-700 border border-yellow-300 px-1.5 py-0.5 rounded flex items-center gap-0.5">
                                  <AlertTriangle className="h-3 w-3" />
                                  権限未戻し
                                </span>
                              )}
                            </div>
                            {/* メタ情報行 */}
                            <div className="flex items-center gap-3 mt-1 text-xs text-gray-500">
                              {proposal.proposalNumber && (
                                <span className="font-mono">{proposal.proposalNumber}</span>
                              )}
                              {proposal.assignedTo && (
                                <span>担当: {proposal.assignedTo}</span>
                              )}
                              {formatDate(proposal.sentAt) && (
                                <span>送付: {formatDate(proposal.sentAt)}</span>
                              )}
                            </div>
                            {/* 備考 */}
                            {proposal.note && (
                              <p className="text-xs text-gray-400 mt-1 truncate max-w-[400px]">
                                {proposal.note}
                              </p>
                            )}
                          </div>

                          {/* アクションボタン */}
                          <div className="flex items-center gap-0.5 shrink-0">
                            {/* ファイル/URLリンク */}
                            {proposal.filePath && (
                              <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => window.open(proposal.filePath!, "_blank")}
                                className="h-8 px-2 text-blue-600"
                                title={proposal.fileName || "PDF"}
                              >
                                <FileText className="h-4 w-4" />
                              </Button>
                            )}
                            {proposal.externalUrl && !proposal.sourceProposalId && (
                              <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => window.open(proposal.externalUrl!, "_blank")}
                                className="h-8 px-2 text-green-600"
                                title={getExternalServiceLabel(proposal.externalService) || "外部リンク"}
                              >
                                <ExternalLink className="h-4 w-4" />
                              </Button>
                            )}

                            <div className="w-px h-5 bg-gray-200 mx-0.5" />

                            {/* 提案書エディタへのリンク */}
                            {proposal.hasProposalContent && !proposal.sourceProposalId && (
                              <Link href={`/stp/proposals/${proposal.id}`}>
                                <Button variant="ghost" size="sm" className="h-8 px-2" title="提案書エディタ">
                                  <FileEdit className="h-4 w-4 text-orange-500" />
                                </Button>
                              </Link>
                            )}
                            {proposal.sourceProposalId && (
                              <Link href={`/stp/proposals/${proposal.sourceProposalId}`}>
                                <Button variant="ghost" size="sm" className="h-8 px-2" title="リード提案書エディタ">
                                  <FileEdit className="h-4 w-4 text-blue-500" />
                                </Button>
                              </Link>
                            )}
                            <Button
                              variant="ghost"
                              size="sm"
                              className="h-8 px-2"
                              onClick={() => handleEdit(proposal)}
                              title="編集"
                            >
                              <Pencil className="h-4 w-4 text-gray-500" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="sm"
                              className="h-8 px-2"
                              onClick={() => handleDelete(proposal.id)}
                              title="削除"
                            >
                              <Trash2 className="h-4 w-4 text-red-400" />
                            </Button>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-12 text-gray-400 text-sm">
                    提案書が登録されていません
                  </div>
                )}
              </TabsContent>

              <TabsContent value="editor" className="mt-4">
                <div className="space-y-2">
                  {editorProposals.map((ep) => (
                    <Link key={ep.id} href={`/stp/proposals/${ep.id}`} className="block border rounded-lg p-4 hover:bg-gray-50/50 transition-colors">
                      <div className="flex items-center justify-between gap-2">
                        <div className="flex items-center gap-2.5 min-w-0">
                          <FileEdit className="h-5 w-5 text-orange-500 shrink-0" />
                          <span className="font-medium text-sm truncate">{ep.title}</span>
                        </div>
                        <ExternalLink className="h-4 w-4 text-gray-400 shrink-0" />
                      </div>
                      <div className="flex items-center gap-3 mt-1.5 ml-[30px] text-xs text-gray-500">
                        <span className="font-mono">{ep.proposalNumber || "-"}</span>
                        <span>{new Date(ep.createdAt).toLocaleDateString("ja-JP")}</span>
                      </div>
                    </Link>
                  ))}
                </div>
              </TabsContent>
            </Tabs>
          ) : (
            <>
              {/* エディタ提案書がない場合: タブなしで直接表示 */}
              {/* 権限未戻し警告バナー */}
              {totalUnlockedCount > 0 && (
                <div className="flex items-center gap-2 rounded-lg border border-yellow-300 bg-yellow-50 px-4 py-2.5">
                  <AlertTriangle className="h-4 w-4 text-yellow-600 shrink-0" />
                  <span className="text-sm text-yellow-800 flex-1">
                    編集権限が戻されていないスライドがあります（{totalUnlockedCount}件）
                  </span>
                  <Button
                    variant="outline"
                    size="sm"
                    className="h-7 text-xs border-yellow-400 hover:bg-yellow-100"
                    onClick={handleLockAllSlides}
                    disabled={isLockingAll}
                  >
                    <Lock className="h-3 w-3 mr-1" />
                    {isLockingAll ? "処理中..." : "すべての権限を戻す"}
                  </Button>
                </div>
              )}

              {/* フォーム（折りたたみ） */}
              {formOpen && (
                <div className="border rounded-lg p-4 bg-gray-50/80">
                  <div className="flex justify-between items-center mb-3">
                    <h3 className="font-medium text-sm">
                      {editingId ? "提案書を編集" : "新規提案書"}
                    </h3>
                    <Button variant="ghost" size="sm" onClick={resetForm} className="h-7 w-7 p-0">
                      <X className="h-4 w-4" />
                    </Button>
                  </div>

                  <form onSubmit={handleSubmit} className="space-y-3">
                    {/* 1行目: タイトル + ステータス */}
                    <div className="grid grid-cols-3 gap-3">
                      <div className="col-span-2 space-y-1">
                        <Label className="text-xs">
                          タイトル <span className="text-red-500">*</span>
                        </Label>
                        <Input
                          value={formData.title}
                          onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                          placeholder="提案書タイトル"
                          className="h-9"
                        />
                      </div>
                      <div className="space-y-1">
                        <Label className="text-xs">ステータス</Label>
                        <Select
                          value={formData.status}
                          onValueChange={(value) => setFormData({ ...formData, status: value })}
                        >
                          <SelectTrigger className="h-9">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            {statusOptions.map((option) => (
                              <SelectItem key={option.value} value={option.value}>
                                {option.label}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                    </div>

                    {/* 2行目: 担当者 + 送付日 */}
                    <div className="grid grid-cols-3 gap-3">
                      <div className="space-y-1">
                        <Label className="text-xs">担当者</Label>
                        <Select
                          value={formData.assignedTo}
                          onValueChange={(value) => setFormData({ ...formData, assignedTo: value })}
                        >
                          <SelectTrigger className="h-9">
                            <SelectValue placeholder="選択" />
                          </SelectTrigger>
                          <SelectContent>
                            {staffOptions.map((option) => (
                              <SelectItem key={option.value} value={option.value}>
                                {option.label}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                      <div className="space-y-1">
                        <Label className="text-xs">送付日</Label>
                        <DatePicker
                          selected={formData.sentAt}
                          onChange={(date: Date | null) => setFormData({ ...formData, sentAt: date })}
                          dateFormat="yyyy/MM/dd"
                          locale="ja"
                          placeholderText="日付を選択"
                          isClearable
                          className={datePickerClassName}
                          wrapperClassName="w-full"
                          calendarClassName="shadow-lg"
                        />
                      </div>
                    </div>

                    {/* ファイルアップロード */}
                    <div className="space-y-1">
                      <Label className="text-xs">提案書ファイル</Label>
                      <FileUpload
                        value={{
                          filePath: formData.filePath || null,
                          fileName: formData.fileName || null,
                        }}
                        onChange={(newValue) => {
                          setFormData({
                            ...formData,
                            filePath: newValue.filePath || "",
                            fileName: newValue.fileName || "",
                          });
                        }}
                      />
                    </div>

                    {/* 詳細設定（トグル） */}
                    <button
                      type="button"
                      className="flex items-center gap-1 text-xs text-gray-500 hover:text-gray-700"
                      onClick={() => setShowAdvanced(!showAdvanced)}
                    >
                      {showAdvanced ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}
                      外部URL・備考
                    </button>

                    {showAdvanced && (
                      <div className="space-y-3 pt-1">
                        <div className="grid grid-cols-2 gap-3">
                          <div className="space-y-1">
                            <Label className="text-xs">外部URL</Label>
                            <Input
                              value={formData.externalUrl}
                              onChange={(e) => setFormData({ ...formData, externalUrl: e.target.value })}
                              placeholder="https://..."
                              className="h-9"
                            />
                          </div>
                          <div className="space-y-1">
                            <Label className="text-xs">外部サービス</Label>
                            <Select
                              value={formData.externalService || "__none__"}
                              onValueChange={(value) => setFormData({ ...formData, externalService: value === "__none__" ? "" : value })}
                            >
                              <SelectTrigger className="h-9">
                                <SelectValue placeholder="選択" />
                              </SelectTrigger>
                              <SelectContent>
                                <SelectItem value="__none__" className="text-gray-400">選択なし</SelectItem>
                                {externalServiceOptions.map((option) => (
                                  <SelectItem key={option.value} value={option.value}>
                                    {option.label}
                                  </SelectItem>
                                ))}
                              </SelectContent>
                            </Select>
                          </div>
                        </div>
                        <div className="space-y-1">
                          <Label className="text-xs">備考</Label>
                          <Textarea
                            value={formData.note}
                            onChange={(e) => setFormData({ ...formData, note: e.target.value })}
                            placeholder="備考"
                            rows={2}
                            className="text-sm"
                          />
                        </div>
                      </div>
                    )}

                    <div className="flex justify-end gap-2 pt-1">
                      <Button type="button" variant="outline" size="sm" onClick={resetForm}>
                        キャンセル
                      </Button>
                      <Button type="submit" size="sm" disabled={isSubmitting}>
                        {isSubmitting ? "保存中..." : "保存"}
                      </Button>
                    </div>
                  </form>
                </div>
              )}

              {/* 提案書一覧（カードレイアウト） */}
              {initialLoading ? (
                <div className="text-center py-8 text-gray-500 text-sm">
                  読み込み中...
                </div>
              ) : localProposals.length > 0 ? (
                <div className="space-y-2">
                  {localProposals.map((proposal) => (
                    <div
                      key={proposal.id}
                      className="border rounded-lg p-3 hover:bg-gray-50/50 transition-colors"
                    >
                      {/* 上段: タイトル行 */}
                      <div className="flex items-start justify-between gap-2">
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 flex-wrap">
                            <span className="font-medium text-sm truncate">
                              {proposal.title}
                            </span>
                            <Badge
                              variant="secondary"
                              className={`text-[10px] px-1.5 py-0 h-5 ${statusColors[proposal.status] || ""}`}
                            >
                              {getStatusLabel(proposal.status)}
                            </Badge>
                            {proposal.isAutoGenerated && (
                              <span className="text-[10px] bg-blue-50 text-blue-600 px-1.5 py-0.5 rounded">
                                自動生成
                              </span>
                            )}
                            {proposal.slideVersion && (
                              <span className="text-[10px] bg-purple-50 text-purple-600 px-1.5 py-0.5 rounded">
                                ver.{proposal.slideVersion}
                              </span>
                            )}
                          </div>
                          {/* メタ情報行 */}
                          <div className="flex items-center gap-3 mt-1 text-xs text-gray-500">
                            {proposal.proposalNumber && (
                              <span className="font-mono">{proposal.proposalNumber}</span>
                            )}
                            {proposal.assignedTo && (
                              <span>担当: {proposal.assignedTo}</span>
                            )}
                            {formatDate(proposal.sentAt) && (
                              <span>送付: {formatDate(proposal.sentAt)}</span>
                            )}
                          </div>
                          {/* 備考 */}
                          {proposal.note && (
                            <p className="text-xs text-gray-400 mt-1 truncate max-w-[400px]">
                              {proposal.note}
                            </p>
                          )}
                        </div>

                        {/* アクションボタン */}
                        <div className="flex items-center gap-0.5 shrink-0">
                          {/* ファイル/URLリンク */}
                          {proposal.filePath && (
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => window.open(proposal.filePath!, "_blank")}
                              className="h-8 px-2 text-blue-600"
                              title={proposal.fileName || "PDF"}
                            >
                              <FileText className="h-4 w-4" />
                            </Button>
                          )}
                          {proposal.externalUrl && !proposal.sourceProposalId && (
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => window.open(proposal.externalUrl!, "_blank")}
                              className="h-8 px-2 text-green-600"
                              title={getExternalServiceLabel(proposal.externalService) || "外部リンク"}
                            >
                              <ExternalLink className="h-4 w-4" />
                            </Button>
                          )}

                          <div className="w-px h-5 bg-gray-200 mx-0.5" />

                          {/* 提案書エディタへのリンク */}
                          {proposal.hasProposalContent && !proposal.sourceProposalId && (
                            <Link href={`/stp/proposals/${proposal.id}`}>
                              <Button variant="ghost" size="sm" className="h-8 px-2" title="提案書エディタ">
                                <FileEdit className="h-4 w-4 text-orange-500" />
                              </Button>
                            </Link>
                          )}
                          {proposal.sourceProposalId && (
                            <Link href={`/stp/proposals/${proposal.sourceProposalId}`}>
                              <Button variant="ghost" size="sm" className="h-8 px-2" title="リード提案書エディタ">
                                <FileEdit className="h-4 w-4 text-blue-500" />
                              </Button>
                            </Link>
                          )}
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-8 px-2"
                            onClick={() => handleEdit(proposal)}
                            title="編集"
                          >
                            <Pencil className="h-4 w-4 text-gray-500" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-8 px-2"
                            onClick={() => handleDelete(proposal.id)}
                            title="削除"
                          >
                            <Trash2 className="h-4 w-4 text-red-400" />
                          </Button>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-12 text-gray-400 text-sm">
                  提案書が登録されていません
                </div>
              )}
            </>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
