-- AlterTable
ALTER TABLE "stp_expense_records" ADD COLUMN     "accountingExternalId" VARCHAR(100),
ADD COLUMN     "accountingService" VARCHAR(30),
ADD COLUMN     "accountingStatus" VARCHAR(20) NOT NULL DEFAULT 'unprocessed',
ADD COLUMN     "accountingSyncedAt" TIMESTAMP(3),
ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "stp_revenue_records" ADD COLUMN     "accountingExternalId" VARCHAR(100),
ADD COLUMN     "accountingService" VARCHAR(30),
ADD COLUMN     "accountingStatus" VARCHAR(20) NOT NULL DEFAULT 'unprocessed',
ADD COLUMN     "accountingSyncedAt" TIMESTAMP(3),
ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE "stp_invoices" (
    "id" SERIAL NOT NULL,
    "direction" VARCHAR(20) NOT NULL,
    "stpCompanyId" INTEGER,
    "agentId" INTEGER,
    "revenueRecordId" INTEGER,
    "expenseRecordId" INTEGER,
    "invoiceNumber" VARCHAR(50),
    "invoiceDate" DATE,
    "dueDate" DATE,
    "totalAmount" INTEGER,
    "taxAmount" INTEGER,
    "status" VARCHAR(20) NOT NULL DEFAULT 'draft',
    "filePath" TEXT,
    "fileName" VARCHAR(200),
    "templateId" VARCHAR(50),
    "templateData" JSONB,
    "note" TEXT,
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "stp_invoices_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "stp_invoices_direction_idx" ON "stp_invoices"("direction");

-- CreateIndex
CREATE INDEX "stp_invoices_stpCompanyId_idx" ON "stp_invoices"("stpCompanyId");

-- CreateIndex
CREATE INDEX "stp_invoices_agentId_idx" ON "stp_invoices"("agentId");

-- CreateIndex
CREATE INDEX "stp_invoices_status_idx" ON "stp_invoices"("status");

-- CreateIndex
CREATE INDEX "stp_expense_records_accountingStatus_idx" ON "stp_expense_records"("accountingStatus");

-- CreateIndex
CREATE INDEX "stp_revenue_records_accountingStatus_idx" ON "stp_revenue_records"("accountingStatus");

-- AddForeignKey
ALTER TABLE "stp_invoices" ADD CONSTRAINT "stp_invoices_stpCompanyId_fkey" FOREIGN KEY ("stpCompanyId") REFERENCES "stp_companies"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stp_invoices" ADD CONSTRAINT "stp_invoices_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "stp_agents"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stp_invoices" ADD CONSTRAINT "stp_invoices_revenueRecordId_fkey" FOREIGN KEY ("revenueRecordId") REFERENCES "stp_revenue_records"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "stp_invoices" ADD CONSTRAINT "stp_invoices_expenseRecordId_fkey" FOREIGN KEY ("expenseRecordId") REFERENCES "stp_expense_records"("id") ON DELETE SET NULL ON UPDATE CASCADE;
