"use client";

import { useState, useEffect, useCallback } from "react";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Combobox } from "@/components/ui/combobox";
import { processAsNewCompany, processWithExistingCompany, rejectSubmission, updateSubmission } from "./actions";
import { toast } from "sonner";
import { Eye, Building2, Link2, X, Pencil, AlertTriangle, FileText, ExternalLink } from "lucide-react";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";

type Proposal = {
  id: number;
  proposalNumber: string | null;
  title: string;
  status: string;
  filePath: string | null;
  fileName: string | null;
  externalUrl: string | null;
  externalService: string | null;
  isAutoGenerated: boolean;
};

type Submission = {
  id: number;
  companyName: string;
  contactName: string;
  contactEmail: string;
  contactPhone: string | null;
  agentId: number;
  agentName: string;
  status: string;
  submittedAt: string;
  processedAt: string | null;
  processingNote: string | null;
  masterCompanyId: number | null;
  pastHiringJobTypes: string[];
  pastRecruitingCostAgency: number | null;
  pastRecruitingCostAds: number | null;
  pastRecruitingCostReferral: number | null;
  pastRecruitingCostOther: number | null;
  pastHiringCount: number | null;
  desiredJobTypes: string[];
  annualBudget: number | null;
  annualHiringTarget: number | null;
  hiringAreas: string[];
  hiringTimeline: string | null;
  ageRangeMin: number | null;
  ageRangeMax: number | null;
  requiredConditions: string | null;
  preferredConditions: string | null;
  proposals: Proposal[];
};

type CompanyOption = {
  value: string;
  label: string;
  companyName: string;
  stpAgentId: number | null;
  stpAgentName: string | null;
};

type Props = {
  submissions: Submission[];
  companyOptions: CompanyOption[];
};

const POLLING_INTERVAL = 10000; // 10秒

const statusLabels: Record<string, { label: string; variant: "default" | "secondary" | "destructive" | "outline" }> = {
  pending: { label: "未処理", variant: "destructive" },
  processed: { label: "処理済", variant: "default" },
  rejected: { label: "却下", variant: "secondary" },
};

export function SubmissionsTable({ submissions: initialSubmissions, companyOptions: initialCompanyOptions }: Props) {
  // ポーリングで更新されるデータ
  const [submissions, setSubmissions] = useState<Submission[]>(initialSubmissions);
  const [companyOptions, setCompanyOptions] = useState<CompanyOption[]>(initialCompanyOptions);

  const [selectedSubmission, setSelectedSubmission] = useState<Submission | null>(null);
  const [detailModalOpen, setDetailModalOpen] = useState(false);
  const [processModalOpen, setProcessModalOpen] = useState(false);
  const [editModalOpen, setEditModalOpen] = useState(false);
  const [confirmDialogOpen, setConfirmDialogOpen] = useState(false);
  const [processType, setProcessType] = useState<"new" | "existing" | "reject">("new");
  const [selectedCompanyId, setSelectedCompanyId] = useState<string>("");
  const [processingNote, setProcessingNote] = useState("");
  const [isProcessing, setIsProcessing] = useState(false);
  const [overwriteAgent, setOverwriteAgent] = useState(false);
  const [companyNameChoice, setCompanyNameChoice] = useState<"master" | "form">("master");
  const [companyNameConfirmOpen, setCompanyNameConfirmOpen] = useState(false);

  // 編集フォーム用の状態
  const [editForm, setEditForm] = useState({
    companyName: "",
    contactName: "",
    contactEmail: "",
    contactPhone: "",
    masterCompanyId: "",
    pastRecruitingCostAgency: "",
    pastRecruitingCostAds: "",
    pastRecruitingCostReferral: "",
    pastRecruitingCostOther: "",
    pastHiringCount: "",
    annualBudget: "",
    annualHiringTarget: "",
    hiringTimeline: "",
    ageRangeMin: "",
    ageRangeMax: "",
    requiredConditions: "",
    preferredConditions: "",
    overwriteAgent: false,
  });

  // ポーリングでデータを更新
  const fetchData = useCallback(async () => {
    try {
      const res = await fetch('/api/stp/lead-submissions');
      if (res.ok) {
        const data = await res.json();
        setSubmissions(data.submissions);
        setCompanyOptions(data.companyOptions);
      }
    } catch (error) {
      console.error('Failed to fetch submissions:', error);
    }
  }, []);

  // ポーリング設定
  useEffect(() => {
    const interval = setInterval(fetchData, POLLING_INTERVAL);
    return () => clearInterval(interval);
  }, [fetchData]);

  // 初期データが変更された場合も更新（Server Componentから渡された新しいデータ）
  useEffect(() => {
    setSubmissions(initialSubmissions);
  }, [initialSubmissions]);

  useEffect(() => {
    setCompanyOptions(initialCompanyOptions);
  }, [initialCompanyOptions]);

  // 日時はサーバー側でフォーマット済みなのでそのまま表示
  const formatDate = (dateStr: string | null) => {
    return dateStr || "-";
  };

  const formatCurrency = (value: number | null) => {
    if (value === null) return "-";
    return `${value.toLocaleString()}円`;
  };

  const openDetailModal = (submission: Submission) => {
    setSelectedSubmission(submission);
    setDetailModalOpen(true);
  };

  const openProcessModal = (submission: Submission, type: "new" | "existing" | "reject") => {
    setSelectedSubmission(submission);
    setProcessType(type);
    setSelectedCompanyId("");
    setProcessingNote("");
    setOverwriteAgent(false);
    setCompanyNameChoice("master");
    setProcessModalOpen(true);
  };

  // 選択された企業のSTP代理店情報を取得
  const getSelectedCompanyAgentInfo = () => {
    if (!selectedCompanyId) return null;
    const company = companyOptions.find((c) => c.value === selectedCompanyId);
    return company ? { agentId: company.stpAgentId, agentName: company.stpAgentName } : null;
  };

  // 代理店が異なるかどうか（紐付け処理用）
  const isAgentDifferent = () => {
    if (!selectedSubmission || !selectedCompanyId) return false;
    const companyAgentInfo = getSelectedCompanyAgentInfo();
    if (!companyAgentInfo?.agentId) return false; // STP未登録なら異なるとは言えない
    return companyAgentInfo.agentId !== selectedSubmission.agentId;
  };

  // 編集フォームで選択された企業の代理店情報を取得
  const getEditFormCompanyAgentInfo = () => {
    if (!editForm.masterCompanyId) return null;
    const company = companyOptions.find((c) => c.value === editForm.masterCompanyId);
    return company ? { agentId: company.stpAgentId, agentName: company.stpAgentName } : null;
  };

  // 編集フォームで代理店が異なるかどうか
  const isEditAgentDifferent = () => {
    if (!selectedSubmission || !editForm.masterCompanyId) return false;
    const companyAgentInfo = getEditFormCompanyAgentInfo();
    if (!companyAgentInfo?.agentId) return false; // STP未登録なら異なるとは言えない
    return companyAgentInfo.agentId !== selectedSubmission.agentId;
  };

  // 企業名が異なるかどうか（紐付け処理用）
  const isCompanyNameDifferent = () => {
    if (!selectedSubmission || !selectedCompanyId) return false;
    const company = companyOptions.find((c) => c.value === selectedCompanyId);
    if (!company) return false;
    return company.companyName !== selectedSubmission.companyName;
  };

  // 選択された企業の企業名を取得
  const getSelectedCompanyName = () => {
    const company = companyOptions.find((c) => c.value === selectedCompanyId);
    return company?.companyName || null;
  };

  const openEditModal = (submission: Submission) => {
    setSelectedSubmission(submission);
    setEditForm({
      companyName: submission.companyName,
      contactName: submission.contactName,
      contactEmail: submission.contactEmail,
      contactPhone: submission.contactPhone || "",
      masterCompanyId: submission.masterCompanyId ? String(submission.masterCompanyId) : "",
      pastRecruitingCostAgency: submission.pastRecruitingCostAgency?.toString() || "",
      pastRecruitingCostAds: submission.pastRecruitingCostAds?.toString() || "",
      pastRecruitingCostReferral: submission.pastRecruitingCostReferral?.toString() || "",
      pastRecruitingCostOther: submission.pastRecruitingCostOther?.toString() || "",
      pastHiringCount: submission.pastHiringCount?.toString() || "",
      annualBudget: submission.annualBudget?.toString() || "",
      annualHiringTarget: submission.annualHiringTarget?.toString() || "",
      hiringTimeline: submission.hiringTimeline || "",
      ageRangeMin: submission.ageRangeMin?.toString() || "",
      ageRangeMax: submission.ageRangeMax?.toString() || "",
      requiredConditions: submission.requiredConditions || "",
      preferredConditions: submission.preferredConditions || "",
      overwriteAgent: false,
    });
    setEditModalOpen(true);
  };

  const handleProcess = async () => {
    if (!selectedSubmission) return;

    // 紐付け処理で企業名が異なる場合は確認ダイアログを表示
    if (processType === "existing" && selectedCompanyId && isCompanyNameDifferent()) {
      setCompanyNameConfirmOpen(true);
      return;
    }

    await executeProcess();
  };

  const executeProcess = async () => {
    if (!selectedSubmission) return;

    setIsProcessing(true);
    try {
      if (processType === "new") {
        await processAsNewCompany(selectedSubmission.id, processingNote || undefined);
        toast.success("新規企業として登録しました");
      } else if (processType === "existing") {
        if (!selectedCompanyId) {
          toast.error("企業を選択してください");
          setIsProcessing(false);
          return;
        }
        // 企業名が異なる場合はcompanyNameUnificationを渡す
        const companyNameUnification = isCompanyNameDifferent() ? companyNameChoice : null;
        await processWithExistingCompany(
          selectedSubmission.id,
          Number(selectedCompanyId),
          processingNote || undefined,
          overwriteAgent,
          companyNameUnification
        );
        toast.success("既存企業に紐付けました");
      } else {
        await rejectSubmission(selectedSubmission.id, processingNote || undefined);
        toast.success("却下しました");
      }
      setProcessModalOpen(false);
      setCompanyNameConfirmOpen(false);
    } catch (error) {
      const message = error instanceof Error ? error.message : "処理に失敗しました";
      toast.error(message);
    } finally {
      setIsProcessing(false);
    }
  };

  const handleEditSubmit = () => {
    setConfirmDialogOpen(true);
  };

  const handleEditConfirm = async () => {
    if (!selectedSubmission) return;

    setIsProcessing(true);
    try {
      await updateSubmission(selectedSubmission.id, {
        companyName: editForm.companyName,
        contactName: editForm.contactName,
        contactEmail: editForm.contactEmail,
        contactPhone: editForm.contactPhone || null,
        masterCompanyId: editForm.masterCompanyId ? Number(editForm.masterCompanyId) : null,
        pastRecruitingCostAgency: editForm.pastRecruitingCostAgency ? Number(editForm.pastRecruitingCostAgency) : null,
        pastRecruitingCostAds: editForm.pastRecruitingCostAds ? Number(editForm.pastRecruitingCostAds) : null,
        pastRecruitingCostReferral: editForm.pastRecruitingCostReferral ? Number(editForm.pastRecruitingCostReferral) : null,
        pastRecruitingCostOther: editForm.pastRecruitingCostOther ? Number(editForm.pastRecruitingCostOther) : null,
        pastHiringCount: editForm.pastHiringCount ? Number(editForm.pastHiringCount) : null,
        annualBudget: editForm.annualBudget ? Number(editForm.annualBudget) : null,
        annualHiringTarget: editForm.annualHiringTarget ? Number(editForm.annualHiringTarget) : null,
        hiringTimeline: editForm.hiringTimeline || null,
        ageRangeMin: editForm.ageRangeMin ? Number(editForm.ageRangeMin) : null,
        ageRangeMax: editForm.ageRangeMax ? Number(editForm.ageRangeMax) : null,
        requiredConditions: editForm.requiredConditions || null,
        preferredConditions: editForm.preferredConditions || null,
        overwriteAgent: editForm.overwriteAgent,
      });
      toast.success("更新しました");
      setEditModalOpen(false);
      setConfirmDialogOpen(false);
    } catch (error) {
      const message = error instanceof Error ? error.message : "更新に失敗しました";
      toast.error(message);
    } finally {
      setIsProcessing(false);
    }
  };

  const pendingSubmissions = submissions.filter((s) => s.status === "pending");
  const processedSubmissions = submissions.filter((s) => s.status !== "pending");

  // 紐付け企業名を取得
  const getLinkedCompanyName = (masterCompanyId: number | null) => {
    if (!masterCompanyId) return null;
    const company = companyOptions.find((c) => c.value === String(masterCompanyId));
    return company?.label || `ID: ${masterCompanyId}`;
  };

  return (
    <div className="space-y-8">
      {/* 未処理 */}
      <div>
        <h3 className="text-lg font-semibold mb-4">未処理（{pendingSubmissions.length}件）</h3>
        {pendingSubmissions.length === 0 ? (
          <p className="text-gray-500 text-sm">未処理の回答はありません</p>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>受信日時</TableHead>
                <TableHead>会社名</TableHead>
                <TableHead>担当者</TableHead>
                <TableHead>メール</TableHead>
                <TableHead>代理店</TableHead>
                <TableHead>提案書</TableHead>
                <TableHead>操作</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {pendingSubmissions.map((submission) => (
                <TableRow key={submission.id}>
                  <TableCell className="whitespace-nowrap">
                    {formatDate(submission.submittedAt)}
                  </TableCell>
                  <TableCell className="font-medium">{submission.companyName}</TableCell>
                  <TableCell>{submission.contactName}</TableCell>
                  <TableCell>{submission.contactEmail}</TableCell>
                  <TableCell>{submission.agentName}</TableCell>
                  <TableCell>
                    {submission.proposals.length > 0 ? (
                      submission.proposals[0].filePath ? (
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => window.open(submission.proposals[0].filePath!, "_blank")}
                          className="flex items-center gap-1"
                        >
                          <FileText className="h-4 w-4 text-blue-600" />
                          <span className="max-w-[100px] truncate text-xs">
                            {submission.proposals[0].fileName || "提案書"}
                          </span>
                          <ExternalLink className="h-3 w-3" />
                        </Button>
                      ) : submission.proposals[0].externalUrl ? (
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => window.open(submission.proposals[0].externalUrl!, "_blank")}
                          className="flex items-center gap-1"
                        >
                          <FileText className="h-4 w-4 text-green-600" />
                          <span className="max-w-[100px] truncate text-xs">
                            {submission.proposals[0].title || "提案書"}
                          </span>
                          <ExternalLink className="h-3 w-3" />
                        </Button>
                      ) : (
                        <span className="text-xs text-gray-400">
                          {submission.proposals.length}件
                        </span>
                      )
                    ) : (
                      <span className="text-gray-400">-</span>
                    )}
                  </TableCell>
                  <TableCell>
                    <div className="flex gap-2">
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => openDetailModal(submission)}
                        title="詳細"
                      >
                        <Eye className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => openEditModal(submission)}
                        title="編集"
                      >
                        <Pencil className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => openProcessModal(submission, "new")}
                      >
                        <Building2 className="h-4 w-4 mr-1" />
                        新規
                      </Button>
                      <Button
                        variant="outline"
                        size="sm"
                        onClick={() => openProcessModal(submission, "existing")}
                      >
                        <Link2 className="h-4 w-4 mr-1" />
                        紐付け
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => openProcessModal(submission, "reject")}
                        title="却下"
                      >
                        <X className="h-4 w-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        )}
      </div>

      {/* 処理済み */}
      <div>
        <h3 className="text-lg font-semibold mb-4">処理済み（{processedSubmissions.length}件）</h3>
        {processedSubmissions.length === 0 ? (
          <p className="text-gray-500 text-sm">処理済みの回答はありません</p>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>受信日時</TableHead>
                <TableHead>会社名</TableHead>
                <TableHead>担当者</TableHead>
                <TableHead>代理店</TableHead>
                <TableHead>紐付け企業</TableHead>
                <TableHead>提案書</TableHead>
                <TableHead>ステータス</TableHead>
                <TableHead>処理日時</TableHead>
                <TableHead>操作</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {processedSubmissions.map((submission) => (
                <TableRow key={submission.id}>
                  <TableCell className="whitespace-nowrap">
                    {formatDate(submission.submittedAt)}
                  </TableCell>
                  <TableCell className="font-medium">{submission.companyName}</TableCell>
                  <TableCell>{submission.contactName}</TableCell>
                  <TableCell>{submission.agentName}</TableCell>
                  <TableCell className="max-w-[200px] truncate">
                    {getLinkedCompanyName(submission.masterCompanyId) || "-"}
                  </TableCell>
                  <TableCell>
                    {submission.proposals.length > 0 ? (
                      submission.proposals[0].filePath ? (
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => window.open(submission.proposals[0].filePath!, "_blank")}
                          className="flex items-center gap-1"
                        >
                          <FileText className="h-4 w-4 text-blue-600" />
                          <span className="max-w-[100px] truncate text-xs">
                            {submission.proposals[0].fileName || "提案書"}
                          </span>
                          <ExternalLink className="h-3 w-3" />
                        </Button>
                      ) : submission.proposals[0].externalUrl ? (
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => window.open(submission.proposals[0].externalUrl!, "_blank")}
                          className="flex items-center gap-1"
                        >
                          <FileText className="h-4 w-4 text-green-600" />
                          <span className="max-w-[100px] truncate text-xs">
                            {submission.proposals[0].title || "提案書"}
                          </span>
                          <ExternalLink className="h-3 w-3" />
                        </Button>
                      ) : (
                        <span className="text-xs text-gray-400">
                          {submission.proposals.length}件
                        </span>
                      )
                    ) : (
                      <span className="text-gray-400">-</span>
                    )}
                  </TableCell>
                  <TableCell>
                    <Badge variant={statusLabels[submission.status]?.variant || "default"}>
                      {statusLabels[submission.status]?.label || submission.status}
                    </Badge>
                  </TableCell>
                  <TableCell className="whitespace-nowrap">
                    {submission.processedAt ? formatDate(submission.processedAt) : "-"}
                  </TableCell>
                  <TableCell>
                    <div className="flex gap-2">
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => openDetailModal(submission)}
                        title="詳細"
                      >
                        <Eye className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => openEditModal(submission)}
                        title="編集"
                      >
                        <Pencil className="h-4 w-4" />
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        )}
      </div>

      {/* 詳細モーダル */}
      <Dialog open={detailModalOpen} onOpenChange={setDetailModalOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>フォーム回答詳細</DialogTitle>
            <DialogDescription>
              {selectedSubmission && formatDate(selectedSubmission.submittedAt)}に受信
            </DialogDescription>
          </DialogHeader>
          {selectedSubmission && (
            <div className="space-y-6">
              {/* 基本情報 */}
              <div>
                <h4 className="font-semibold border-b pb-2 mb-3">基本情報</h4>
                <dl className="grid grid-cols-2 gap-2 text-sm">
                  <dt className="text-gray-500">会社名</dt>
                  <dd>{selectedSubmission.companyName}</dd>
                  <dt className="text-gray-500">担当者</dt>
                  <dd>{selectedSubmission.contactName}</dd>
                  <dt className="text-gray-500">メール</dt>
                  <dd>{selectedSubmission.contactEmail}</dd>
                  <dt className="text-gray-500">電話</dt>
                  <dd>{selectedSubmission.contactPhone || "-"}</dd>
                  <dt className="text-gray-500">代理店</dt>
                  <dd>{selectedSubmission.agentName}</dd>
                  <dt className="text-gray-500">紐付け企業</dt>
                  <dd>{getLinkedCompanyName(selectedSubmission.masterCompanyId) || "-"}</dd>
                </dl>
              </div>

              {/* 採用実績 */}
              <div>
                <h4 className="font-semibold border-b pb-2 mb-3">採用実績</h4>
                <dl className="grid grid-cols-2 gap-2 text-sm">
                  <dt className="text-gray-500">過去採用職種</dt>
                  <dd>{selectedSubmission.pastHiringJobTypes.join(", ") || "-"}</dd>
                  <dt className="text-gray-500">人材紹介費用</dt>
                  <dd>{formatCurrency(selectedSubmission.pastRecruitingCostAgency)}</dd>
                  <dt className="text-gray-500">求人広告費用</dt>
                  <dd>{formatCurrency(selectedSubmission.pastRecruitingCostAds)}</dd>
                  <dt className="text-gray-500">リファラル費用</dt>
                  <dd>{formatCurrency(selectedSubmission.pastRecruitingCostReferral)}</dd>
                  <dt className="text-gray-500">その他費用</dt>
                  <dd>{formatCurrency(selectedSubmission.pastRecruitingCostOther)}</dd>
                  <dt className="text-gray-500">過去採用人数</dt>
                  <dd>{selectedSubmission.pastHiringCount ? `${selectedSubmission.pastHiringCount}人` : "-"}</dd>
                </dl>
              </div>

              {/* 希望情報 */}
              <div>
                <h4 className="font-semibold border-b pb-2 mb-3">今後の採用計画</h4>
                <dl className="grid grid-cols-2 gap-2 text-sm">
                  <dt className="text-gray-500">希望職種</dt>
                  <dd>{selectedSubmission.desiredJobTypes.join(", ") || "-"}</dd>
                  <dt className="text-gray-500">年間予算</dt>
                  <dd>{formatCurrency(selectedSubmission.annualBudget)}</dd>
                  <dt className="text-gray-500">年間採用予定</dt>
                  <dd>{selectedSubmission.annualHiringTarget ? `${selectedSubmission.annualHiringTarget}人` : "-"}</dd>
                  <dt className="text-gray-500">採用エリア</dt>
                  <dd>{selectedSubmission.hiringAreas.join(", ") || "-"}</dd>
                  <dt className="text-gray-500">採用希望時期</dt>
                  <dd>{selectedSubmission.hiringTimeline || "-"}</dd>
                  <dt className="text-gray-500">採用可能年齢</dt>
                  <dd>
                    {selectedSubmission.ageRangeMin || selectedSubmission.ageRangeMax
                      ? `${selectedSubmission.ageRangeMin || ""}〜${selectedSubmission.ageRangeMax || ""}歳`
                      : "-"}
                  </dd>
                </dl>
                <dl className="mt-2 text-sm">
                  <dt className="text-gray-500">必須条件</dt>
                  <dd className="mt-1 whitespace-pre-wrap">{selectedSubmission.requiredConditions || "-"}</dd>
                  <dt className="text-gray-500 mt-2">希望条件</dt>
                  <dd className="mt-1 whitespace-pre-wrap">{selectedSubmission.preferredConditions || "-"}</dd>
                </dl>
              </div>

              {/* 提案書 */}
              {selectedSubmission.proposals && selectedSubmission.proposals.length > 0 && (
                <div>
                  <h4 className="font-semibold border-b pb-2 mb-3">提案書</h4>
                  <div className="space-y-2">
                    {selectedSubmission.proposals.map((proposal) => (
                      <div
                        key={proposal.id}
                        className="flex items-center justify-between p-3 bg-gray-50 rounded-lg"
                      >
                        <div className="flex-1">
                          <div className="flex items-center gap-2">
                            <span className="font-medium text-sm">{proposal.title}</span>
                            {proposal.isAutoGenerated && (
                              <span className="text-xs bg-blue-100 text-blue-700 px-2 py-0.5 rounded">
                                自動生成
                              </span>
                            )}
                          </div>
                          <div className="text-xs text-gray-500 mt-1">
                            {proposal.proposalNumber && (
                              <span className="font-mono">{proposal.proposalNumber}</span>
                            )}
                            {proposal.proposalNumber && proposal.status && " / "}
                            <span>
                              {proposal.status === "draft" && "下書き"}
                              {proposal.status === "sent" && "送付済み"}
                              {proposal.status === "viewed" && "閲覧済み"}
                              {proposal.status === "accepted" && "受諾"}
                              {proposal.status === "rejected" && "辞退"}
                            </span>
                          </div>
                        </div>
                        <div className="flex items-center gap-2">
                          {proposal.filePath && proposal.fileName && (
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => window.open(proposal.filePath!, "_blank")}
                              className="flex items-center gap-1 text-blue-600"
                              title={proposal.fileName}
                            >
                              <FileText className="h-4 w-4" />
                              <ExternalLink className="h-3 w-3" />
                            </Button>
                          )}
                          {proposal.externalUrl && (
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => window.open(proposal.externalUrl!, "_blank")}
                              className="flex items-center gap-1 text-green-600"
                              title={proposal.externalService || proposal.externalUrl}
                            >
                              <ExternalLink className="h-4 w-4" />
                              {proposal.externalService && (
                                <span className="text-xs">
                                  {proposal.externalService === "canva" && "Canva"}
                                  {proposal.externalService === "google_docs" && "Google Docs"}
                                  {proposal.externalService === "other" && "外部"}
                                </span>
                              )}
                            </Button>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* 処理メモ */}
              {selectedSubmission.processingNote && (
                <div>
                  <h4 className="font-semibold border-b pb-2 mb-3">処理メモ</h4>
                  <p className="text-sm whitespace-pre-wrap">{selectedSubmission.processingNote}</p>
                </div>
              )}
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* 処理モーダル */}
      <Dialog open={processModalOpen} onOpenChange={setProcessModalOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>
              {processType === "new" && "新規企業として登録"}
              {processType === "existing" && "既存企業に紐付け"}
              {processType === "reject" && "却下"}
            </DialogTitle>
            <DialogDescription>
              {selectedSubmission?.companyName}（{selectedSubmission?.contactName}）
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4">
            {processType === "new" && (
              <p className="text-sm text-gray-600">
                新しい企業として全顧客マスタに登録し、STPプロジェクトのリードとして追加します。
              </p>
            )}

            {processType === "existing" && (
              <div className="space-y-4">
                <div className="space-y-2">
                  <Label>紐付ける企業を選択</Label>
                  <Combobox
                    options={companyOptions}
                    value={selectedCompanyId}
                    onChange={(value) => {
                      setSelectedCompanyId(value);
                      setOverwriteAgent(false); // 企業変更時にリセット
                    }}
                    placeholder="企業を検索..."
                  />
                </div>

                {/* 代理店が異なる場合の警告 */}
                {isAgentDifferent() && (
                  <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 space-y-3">
                    <div className="flex items-start gap-2">
                      <AlertTriangle className="h-5 w-5 text-amber-600 flex-shrink-0 mt-0.5" />
                      <div className="text-sm">
                        <p className="font-medium text-amber-800">代理店が異なります</p>
                        <p className="text-amber-700 mt-1">
                          既存の代理店: <span className="font-medium">{getSelectedCompanyAgentInfo()?.agentName}</span>
                        </p>
                        <p className="text-amber-700">
                          フォーム送信元: <span className="font-medium">{selectedSubmission?.agentName}</span>
                        </p>
                      </div>
                    </div>
                    <RadioGroup
                      value={overwriteAgent ? "overwrite" : "keep"}
                      onValueChange={(value) => setOverwriteAgent(value === "overwrite")}
                      className="ml-7"
                    >
                      <div className="flex items-center space-x-2">
                        <RadioGroupItem value="keep" id="keep-agent" />
                        <Label htmlFor="keep-agent" className="text-sm font-normal">
                          既存の代理店を維持
                        </Label>
                      </div>
                      <div className="flex items-center space-x-2">
                        <RadioGroupItem value="overwrite" id="overwrite-agent" />
                        <Label htmlFor="overwrite-agent" className="text-sm font-normal">
                          フォーム送信元の代理店に変更
                        </Label>
                      </div>
                    </RadioGroup>
                  </div>
                )}

                {/* 企業名が異なる場合の警告 */}
                {isCompanyNameDifferent() && (
                  <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 space-y-3">
                    <div className="flex items-start gap-2">
                      <AlertTriangle className="h-5 w-5 text-amber-600 flex-shrink-0 mt-0.5" />
                      <div className="text-sm">
                        <p className="font-medium text-amber-800">企業名が異なります</p>
                        <p className="text-amber-700 mt-1">
                          フォーム回答: <span className="font-medium">{selectedSubmission?.companyName}</span>
                        </p>
                        <p className="text-amber-700">
                          全顧客マスタ: <span className="font-medium">{getSelectedCompanyName()}</span>
                        </p>
                      </div>
                    </div>
                    <RadioGroup
                      value={companyNameChoice}
                      onValueChange={(value) => setCompanyNameChoice(value as "master" | "form")}
                      className="ml-7"
                    >
                      <div className="flex items-center space-x-2">
                        <RadioGroupItem value="master" id="use-master-name" />
                        <Label htmlFor="use-master-name" className="text-sm font-normal">
                          全顧客マスタの企業名に統一
                        </Label>
                      </div>
                      <div className="flex items-center space-x-2">
                        <RadioGroupItem value="form" id="use-form-name" />
                        <Label htmlFor="use-form-name" className="text-sm font-normal">
                          フォーム回答の企業名（{selectedSubmission?.companyName}）に統一
                        </Label>
                      </div>
                    </RadioGroup>
                  </div>
                )}
              </div>
            )}

            {processType === "reject" && (
              <p className="text-sm text-gray-600">
                このフォーム回答を却下します。企業は作成されません。
              </p>
            )}

            <div className="space-y-2">
              <Label htmlFor="processingNote">処理メモ（任意）</Label>
              <Textarea
                id="processingNote"
                value={processingNote}
                onChange={(e) => setProcessingNote(e.target.value)}
                placeholder="処理に関するメモを入力..."
              />
            </div>
          </div>

          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setProcessModalOpen(false)}
              disabled={isProcessing}
            >
              キャンセル
            </Button>
            <Button
              onClick={handleProcess}
              disabled={isProcessing || (processType === "existing" && !selectedCompanyId)}
              variant={processType === "reject" ? "destructive" : "default"}
            >
              {isProcessing ? "処理中..." : "実行"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* 編集モーダル */}
      <Dialog open={editModalOpen} onOpenChange={setEditModalOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>フォーム回答を編集</DialogTitle>
            <DialogDescription>
              {selectedSubmission && formatDate(selectedSubmission.submittedAt)}に受信
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-6">
            {/* 基本情報 */}
            <div className="space-y-4">
              <h4 className="font-semibold border-b pb-2">基本情報</h4>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="edit-companyName">会社名</Label>
                  <Input
                    id="edit-companyName"
                    value={editForm.companyName}
                    onChange={(e) => setEditForm({ ...editForm, companyName: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="edit-contactName">担当者名</Label>
                  <Input
                    id="edit-contactName"
                    value={editForm.contactName}
                    onChange={(e) => setEditForm({ ...editForm, contactName: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="edit-contactEmail">メールアドレス</Label>
                  <Input
                    id="edit-contactEmail"
                    type="email"
                    value={editForm.contactEmail}
                    onChange={(e) => setEditForm({ ...editForm, contactEmail: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="edit-contactPhone">電話番号</Label>
                  <Input
                    id="edit-contactPhone"
                    value={editForm.contactPhone}
                    onChange={(e) => setEditForm({ ...editForm, contactPhone: e.target.value })}
                  />
                </div>
              </div>
              <div className="space-y-2">
                <Label>紐付け企業</Label>
                <Combobox
                  options={[{ value: "", label: "（紐付けなし）", companyName: "", stpAgentId: null, stpAgentName: null }, ...companyOptions]}
                  value={editForm.masterCompanyId}
                  onChange={(value) => setEditForm({ ...editForm, masterCompanyId: value, overwriteAgent: false })}
                  placeholder="企業を検索..."
                />
              </div>

              {/* 代理店が異なる場合の警告 */}
              {isEditAgentDifferent() && (
                <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 space-y-3">
                  <div className="flex items-start gap-2">
                    <AlertTriangle className="h-5 w-5 text-amber-600 flex-shrink-0 mt-0.5" />
                    <div className="text-sm">
                      <p className="font-medium text-amber-800">代理店が異なります</p>
                      <p className="text-amber-700 mt-1">
                        既存の代理店: <span className="font-medium">{getEditFormCompanyAgentInfo()?.agentName}</span>
                      </p>
                      <p className="text-amber-700">
                        フォーム送信元: <span className="font-medium">{selectedSubmission?.agentName}</span>
                      </p>
                    </div>
                  </div>
                  <RadioGroup
                    value={editForm.overwriteAgent ? "overwrite" : "keep"}
                    onValueChange={(value) => setEditForm({ ...editForm, overwriteAgent: value === "overwrite" })}
                    className="ml-7"
                  >
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="keep" id="edit-keep-agent" />
                      <Label htmlFor="edit-keep-agent" className="text-sm font-normal">
                        既存の代理店を維持
                      </Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="overwrite" id="edit-overwrite-agent" />
                      <Label htmlFor="edit-overwrite-agent" className="text-sm font-normal">
                        フォーム送信元の代理店に変更
                      </Label>
                    </div>
                  </RadioGroup>
                </div>
              )}
            </div>

            {/* 採用実績 */}
            <div className="space-y-4">
              <h4 className="font-semibold border-b pb-2">採用実績</h4>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="edit-pastRecruitingCostAgency">人材紹介費用（円）</Label>
                  <Input
                    id="edit-pastRecruitingCostAgency"
                    type="number"
                    value={editForm.pastRecruitingCostAgency}
                    onChange={(e) => setEditForm({ ...editForm, pastRecruitingCostAgency: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="edit-pastRecruitingCostAds">求人広告費用（円）</Label>
                  <Input
                    id="edit-pastRecruitingCostAds"
                    type="number"
                    value={editForm.pastRecruitingCostAds}
                    onChange={(e) => setEditForm({ ...editForm, pastRecruitingCostAds: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="edit-pastRecruitingCostReferral">リファラル費用（円）</Label>
                  <Input
                    id="edit-pastRecruitingCostReferral"
                    type="number"
                    value={editForm.pastRecruitingCostReferral}
                    onChange={(e) => setEditForm({ ...editForm, pastRecruitingCostReferral: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="edit-pastRecruitingCostOther">その他費用（円）</Label>
                  <Input
                    id="edit-pastRecruitingCostOther"
                    type="number"
                    value={editForm.pastRecruitingCostOther}
                    onChange={(e) => setEditForm({ ...editForm, pastRecruitingCostOther: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="edit-pastHiringCount">過去採用人数</Label>
                  <Input
                    id="edit-pastHiringCount"
                    type="number"
                    value={editForm.pastHiringCount}
                    onChange={(e) => setEditForm({ ...editForm, pastHiringCount: e.target.value })}
                  />
                </div>
              </div>
            </div>

            {/* 希望情報 */}
            <div className="space-y-4">
              <h4 className="font-semibold border-b pb-2">採用計画</h4>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="edit-annualBudget">年間予算（円）</Label>
                  <Input
                    id="edit-annualBudget"
                    type="number"
                    value={editForm.annualBudget}
                    onChange={(e) => setEditForm({ ...editForm, annualBudget: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="edit-annualHiringTarget">年間採用予定人数</Label>
                  <Input
                    id="edit-annualHiringTarget"
                    type="number"
                    value={editForm.annualHiringTarget}
                    onChange={(e) => setEditForm({ ...editForm, annualHiringTarget: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="edit-hiringTimeline">採用希望時期</Label>
                  <Input
                    id="edit-hiringTimeline"
                    value={editForm.hiringTimeline}
                    onChange={(e) => setEditForm({ ...editForm, hiringTimeline: e.target.value })}
                  />
                </div>
                <div className="space-y-2 col-span-2 grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="edit-ageRangeMin">採用可能年齢（下限）</Label>
                    <Input
                      id="edit-ageRangeMin"
                      type="number"
                      value={editForm.ageRangeMin}
                      onChange={(e) => setEditForm({ ...editForm, ageRangeMin: e.target.value })}
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="edit-ageRangeMax">採用可能年齢（上限）</Label>
                    <Input
                      id="edit-ageRangeMax"
                      type="number"
                      value={editForm.ageRangeMax}
                      onChange={(e) => setEditForm({ ...editForm, ageRangeMax: e.target.value })}
                    />
                  </div>
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="edit-requiredConditions">必須条件</Label>
                <Textarea
                  id="edit-requiredConditions"
                  value={editForm.requiredConditions}
                  onChange={(e) => setEditForm({ ...editForm, requiredConditions: e.target.value })}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="edit-preferredConditions">希望条件</Label>
                <Textarea
                  id="edit-preferredConditions"
                  value={editForm.preferredConditions}
                  onChange={(e) => setEditForm({ ...editForm, preferredConditions: e.target.value })}
                />
              </div>
            </div>
          </div>

          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setEditModalOpen(false)}
              disabled={isProcessing}
            >
              キャンセル
            </Button>
            <Button onClick={handleEditSubmit} disabled={isProcessing}>
              更新
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* 確認ダイアログ（編集用） */}
      <AlertDialog open={confirmDialogOpen} onOpenChange={setConfirmDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>本当に更新しますか？</AlertDialogTitle>
            <AlertDialogDescription>
              フォーム回答の内容を変更します。この操作は取り消せません。
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={isProcessing}>キャンセル</AlertDialogCancel>
            <AlertDialogAction onClick={handleEditConfirm} disabled={isProcessing}>
              {isProcessing ? "処理中..." : "更新する"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* 企業名統一確認ダイアログ */}
      <AlertDialog open={companyNameConfirmOpen} onOpenChange={setCompanyNameConfirmOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>企業名を統一しますか？</AlertDialogTitle>
            <AlertDialogDescription>
              {companyNameChoice === "master"
                ? `「${getSelectedCompanyName()}」に統一します。フォーム回答の企業名が更新されます。`
                : `「${selectedSubmission?.companyName}」に統一します。全顧客マスタの企業名が更新されます。`
              }
              <br />こちらでよろしいですか？
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={isProcessing}>キャンセル</AlertDialogCancel>
            <AlertDialogAction onClick={executeProcess} disabled={isProcessing}>
              {isProcessing ? "処理中..." : "OK"}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
